// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentMcpTransport } from "./AgentMcpTransport";

export type AgentMcpServer = { name: string, transport: AgentMcpTransport, };
