// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentMcpTransportHttp = { type: "http", url: string, headers?: { [key in string]: string }, };
