// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentMcpServer } from "./AgentMcpServer";
import type { DefinitionScope } from "./DefinitionScope";
import type { ToolPolicy } from "./ToolPolicy";

export type AgentDefinitionEntry = { scope: DefinitionScope, id: string, name: string, description: string, instructions?: string, bootstrap_prompt?: string, skill_names?: Array<string>, mcp_servers: Array<AgentMcpServer>, tool_policy: ToolPolicy, default_backend?: string, include_agent_control: boolean, builtin: boolean, };
