// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentMcpTransportHttp } from "./AgentMcpTransportHttp";
import type { AgentMcpTransportStdio } from "./AgentMcpTransportStdio";

export type AgentMcpTransport = AgentMcpTransportHttp | AgentMcpTransportStdio;
