// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentResult = { agent_id: string, is_running: boolean, message: string | null, error: string | null, summary: string, };
