// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentResult } from "./AgentResult";

export type AwaitAgentsResponse = { ready: Array<AgentResult>, still_running: Array<string>, };
