// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BackendUsageWindow = { id: string, label: string, used_percent: number | null, reset_at_text: string | null, reset_at_unix: bigint | null, window_minutes: bigint | null, };
