// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackendDepResult } from "./BackendDepResult";

export type BackendDependencyStatus = { tycode: BackendDepResult, codex: BackendDepResult, claude: BackendDepResult, kiro: BackendDepResult, gemini: BackendDepResult, };
