// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackendKind } from "./BackendKind";
import type { BackendUsageWindow } from "./BackendUsageWindow";

export type BackendUsageResult = { backend_kind: BackendKind, source: string, captured_at_ms: bigint, plan: string | null, status: string | null, windows: Array<BackendUsageWindow>, details: Array<string>, };
