// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageData } from "./ImageData";
import type { SessionSettingsData } from "./SessionSettingsData";

export type ChatActorMessage = { "UserInput": string } | { "UserInputWithImages": { text: string, images: Array<ImageData>, } } | { "ChangeProvider": string } | "GetSettings" | { "SaveSettings": { settings: SessionSettingsData, persist: boolean, } } | { "SwitchProfile": { profile_name: string, } } | { "SaveProfile": { profile_name: string, } } | "ListProfiles" | "ListSessions" | { "ResumeSession": { session_id: string, } } | { "DeleteSession": { session_id: string, } } | "GetModuleSchemas";
