// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatEvent } from "./ChatEvent";

export type ChatEventPayload = { conversation_id: string, event: ChatEvent, };
