// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContextBreakdown } from "./ContextBreakdown";
import type { ImageData } from "./ImageData";
import type { MessageSender } from "./MessageSender";
import type { ModelInfo } from "./ModelInfo";
import type { ReasoningData } from "./ReasoningData";
import type { TokenUsage } from "./TokenUsage";
import type { ToolUseData } from "./ToolUseData";

export type ChatMessage = { timestamp: bigint, sender: MessageSender, content: string, reasoning?: ReasoningData | null, tool_calls: Array<ToolUseData>, model_info?: ModelInfo | null, token_usage?: TokenUsage | null, context_breakdown?: ContextBreakdown | null, images?: Array<ImageData>, };
