// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatMessage } from "./ChatMessage";
import type { ModelsListData } from "./ModelsListData";
import type { ModuleSchemasData } from "./ModuleSchemasData";
import type { OperationCancelledData } from "./OperationCancelledData";
import type { ProfilesListData } from "./ProfilesListData";
import type { RetryAttemptData } from "./RetryAttemptData";
import type { SessionSettingsData } from "./SessionSettingsData";
import type { SessionStartedData } from "./SessionStartedData";
import type { SessionsListData } from "./SessionsListData";
import type { StreamEndData } from "./StreamEndData";
import type { StreamStartData } from "./StreamStartData";
import type { StreamTextDeltaData } from "./StreamTextDeltaData";
import type { SubprocessExitData } from "./SubprocessExitData";
import type { TaskList } from "./TaskList";
import type { TimingUpdateData } from "./TimingUpdateData";
import type { ToolExecutionCompletedData } from "./ToolExecutionCompletedData";
import type { ToolRequest } from "./ToolRequest";

export type ChatEvent = { "kind": "MessageAdded", "data": ChatMessage } | { "kind": "StreamStart", "data": StreamStartData } | { "kind": "StreamDelta", "data": StreamTextDeltaData } | { "kind": "StreamReasoningDelta", "data": StreamTextDeltaData } | { "kind": "StreamEnd", "data": StreamEndData } | { "kind": "Settings", "data": SessionSettingsData } | { "kind": "TypingStatusChanged", "data": boolean } | { "kind": "ConversationCleared" } | { "kind": "ToolRequest", "data": ToolRequest } | { "kind": "ToolExecutionCompleted", "data": ToolExecutionCompletedData } | { "kind": "OperationCancelled", "data": OperationCancelledData } | { "kind": "RetryAttempt", "data": RetryAttemptData } | { "kind": "TaskUpdate", "data": TaskList } | { "kind": "SessionStarted", "data": SessionStartedData } | { "kind": "SessionsList", "data": SessionsListData } | { "kind": "ProfilesList", "data": ProfilesListData } | { "kind": "ModelsList", "data": ModelsListData } | { "kind": "TimingUpdate", "data": TimingUpdateData } | { "kind": "ModuleSchemas", "data": ModuleSchemasData } | { "kind": "SubprocessStderr", "data": string } | { "kind": "SubprocessExit", "data": SubprocessExitData } | { "kind": "Error", "data": string };
