// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type ClientFrame = { "type": "Invoke", req_id: bigint, command: string, params: JsonValue, } | { "type": "Handshake", req_id: bigint, protocol_version: number, tyde_version: string, last_agent_event_seq: bigint, last_chat_event_seqs: { [key in string]: bigint }, };
