// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuntimeAgent } from "./RuntimeAgent";
import type { JsonValue } from "./serde_json/JsonValue";

export type CollectedAgentResult = { agent: RuntimeAgent, final_message: string | null, changed_files: Array<string>, tool_results: Array<JsonValue>, };
