// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DialogKind } from "./DialogKind";

export type ConfirmDialogParams = { message: string, title?: string, kind?: DialogKind, okLabel?: string, cancelLabel?: string, };
