// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContextBreakdown = { system_prompt_bytes: bigint, tool_io_bytes: bigint, conversation_history_bytes: bigint, reasoning_bytes: bigint, context_injection_bytes: bigint, input_tokens: bigint, context_window: bigint, };
