// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileInfo } from "./FileInfo";

export type ContextInfo = { directory_list_bytes: bigint, files: Array<FileInfo>, };
