// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConversationRegisteredData } from "./ConversationRegisteredData";

export type ConversationRegisteredPayload = { conversation_id: string, data: ConversationRegisteredData, };
