// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConversationSnapshot = { agent_id: string, backend_kind: string, workspace_roots: Array<string>, chat_event_seq: bigint, };
