// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConversationRegisteredData = { agent_id?: string | null, workspace_roots: Array<string>, backend_kind: string, name: string, agent_type?: string | null, parent_agent_id?: string | null, ui_owner_project_id?: string | null, };
