// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackendKind } from "./BackendKind";

export type CreateAdminSubprocessParams = { workspaceRoots: Array<string>, backendKind?: BackendKind, };
