// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackendKind } from "./BackendKind";

export type CreateAgentParams = { workspaceRoots: Array<string>, backendKind?: BackendKind, ephemeral?: boolean, agentDefinitionId?: string, uiOwnerProjectId?: string | null, };
