// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DevInstanceStartResult = { instance_id: bigint, debug_mcp_url: string, status: string, };
