// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DevInstanceStartParams = { projectDir: string, workspacePath?: string, sshHost?: string, agentId?: string, };
