// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DriverMcpHttpServerSettings = { enabled: boolean, autoload: boolean, running: boolean, url: string | null, };
