// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitFileStatusKind } from "./GitFileStatusKind";

export type GitFileStatus = { path: string, status: GitFileStatusKind, staged: boolean, };
