// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConversationSnapshot } from "./ConversationSnapshot";
import type { JsonValue } from "./serde_json/JsonValue";

export type HandshakeResult<Agent = JsonValue, SessionRecord = JsonValue, ProjectRecord = JsonValue> = { protocol_version: number, tyde_version: string, agents: Array<Agent>, conversations: Array<ConversationSnapshot>, instance_id: string | null, session_records: Array<SessionRecord>, projects: Array<ProjectRecord>, };
