// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RemoteKind } from "./RemoteKind";

export type Host = { id: string, label: string, hostname: string, is_local: boolean, remote_kind: RemoteKind, enabled_backends: Array<string>, default_backend: string, };
