// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectRecord } from "./ProjectRecord";

export type HostProjectsChangedPayload = { host_id: string, projects: Array<ProjectRecord>, };
