// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Model = "ClaudeOpus46" | "ClaudeOpus45" | "ClaudeSonnet46" | "ClaudeSonnet45" | "ClaudeHaiku45" | "Gemini3ProPreview" | "Gpt52" | "Gpt51CodexMax" | "KimiK25" | "Gemini3FlashPreview" | "GLM5" | "MinimaxM25" | "Grok41Fast" | "GrokCodeFast1" | "Qwen3Coder" | "GptOss120b" | "OpenRouterAuto" | "None";
