// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelsListEntry } from "./ModelsListEntry";

export type ModelsListData = { models: Array<ModelsListEntry>, };
