// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModuleSchemaInfo } from "./ModuleSchemaInfo";

export type ModuleSchemasData = { schemas: Array<ModuleSchemaInfo>, };
