// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProjectRecord = { id: string, name: string, workspace_path: string, roots: Array<string>, parent_project_id: string | null, workbench_kind: string | null, };
