// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectRecord } from "./ProjectRecord";

export type ProjectsChangedPayload = { projects: Array<ProjectRecord>, };
