// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RemoteTydeServerState } from "./RemoteTydeServerState";

export type RemoteTydeServerStatus = { host_id: string, host: string, state: RemoteTydeServerState, local_version: string, remote_version: string | null, target: string | null, socket_path: string | null, install_path: string | null, installed_versions: Array<string>, installed_client_version: boolean, running: boolean, needs_upgrade: boolean, error: string | null, };
