// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RemoteServerStatus = { status: string, protocol_version: number, tyde_version: string, pid: bigint, };
