// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RemoteControlSettings = { enabled: boolean, running: boolean, socket_path: string | null, connected_clients: bigint, };
