// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RemoteConnectionProgress = { host: string, step: string, status: string, message: string, };
