// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RemoteTydeServerState = "not_installed" | "stopped" | "running_current" | "running_stale" | "running_unknown" | "error";
