// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RuntimeAgent = { agent_id: string, conversation_id: string, ui_owner_project_id?: string | null, workspace_roots: Array<string>, backend_kind: string, parent_agent_id: string | null, name: string, agent_type: string | null, agent_definition_id: string | null, is_running: boolean, summary: string, created_at_ms: bigint, updated_at_ms: bigint, ended_at_ms: bigint | null, last_error: string | null, last_message: string | null, };
