// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuntimeAgentEvent } from "./RuntimeAgentEvent";

export type RuntimeAgentEventBatch = { events: Array<RuntimeAgentEvent>, latest_seq: bigint, };
