// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RuntimeAgentEvent = { seq: bigint, agent_id: string, conversation_id: string, kind: string, is_running: boolean, timestamp_ms: bigint, message: string | null, };
