// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageAttachment } from "./ImageAttachment";

export type SendMessageParams = { conversationId: string, message: string, images?: Array<ImageAttachment>, };
