// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type ServerFrame = { "type": "Result", req_id: bigint, data: JsonValue, } | { "type": "Error", req_id: bigint, error: string, } | { "type": "Event", event: string, seq: bigint | null, payload: JsonValue, } | { "type": "Shutdown", reason: string, };
