// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SessionMetadata = { id: string, title: string, last_modified: bigint, session_id?: string, created_at?: bigint, message_count?: bigint, last_message_preview?: string, preview?: string, workspace_root?: string, backend_kind?: string, };
