// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionMetadata } from "./SessionMetadata";

export type SessionsListData = { sessions: Array<SessionMetadata>, };
