// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SessionRecord = { id: string, host_id: string, backend_session_id: string | null, backend_kind: string, alias: string | null, user_alias: string | null, parent_id: string | null, workspace_root: string | null, workspace_roots: Array<string>, created_at_ms: bigint, updated_at_ms: bigint, message_count: bigint, };
