// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatEvent } from "./ChatEvent";
import type { JsonValue } from "./serde_json/JsonValue";

export type SessionData = { id: string, created_at: bigint, last_modified: bigint, messages: Array<JsonValue>, tracked_files: Array<string>, events: Array<ChatEvent>, };
