// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackendKind } from "./BackendKind";

export type SpawnAgentParams = { workspaceRoots: Array<string>, prompt: string, backendKind?: BackendKind, parentAgentId?: string, uiOwnerProjectId?: string | null, name?: string, ephemeral?: boolean, agentDefinitionId?: string, };
