// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StreamStartData = { message_id?: string, agent: string, model?: string | null, };
