// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Task } from "./Task";

export type TaskList = { title: string, tasks: Array<Task>, };
