// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DurationLike } from "./DurationLike";

export type TimingUpdateData = { waiting_for_human: DurationLike, ai_processing: DurationLike, tool_execution: DurationLike, };
