// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TokenUsage = { input_tokens: bigint, output_tokens: bigint, total_tokens: bigint, cached_prompt_tokens?: bigint, cache_creation_input_tokens?: bigint, reasoning_tokens?: bigint, };
