// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolRequestType } from "./ToolRequestType";

export type ToolRequest = { tool_call_id: string, tool_name: string, tool_type: ToolRequestType, };
