// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolExecutionResult } from "./ToolExecutionResult";

export type ToolExecutionCompletedData = { tool_call_id: string, tool_name: string, tool_result: ToolExecutionResult, success: boolean, error?: string, };
