// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileInfo } from "./FileInfo";
import type { JsonValue } from "./serde_json/JsonValue";

export type ToolExecutionResult = { "kind": "ModifyFile", lines_added: bigint, lines_removed: bigint, } | { "kind": "RunCommand", exit_code: number, stdout: string, stderr: string, } | { "kind": "ReadFiles", files: Array<FileInfo>, } | { "kind": "SearchTypes", types: Array<string>, } | { "kind": "GetTypeDocs", documentation: string, } | { "kind": "Error", short_message: string, detailed_message: string, } | { "kind": "Other", result: JsonValue, };
