// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ToolPolicy = { "mode": "Unrestricted" } | { "mode": "AllowList", "tools": Array<string> } | { "mode": "DenyList", "tools": Array<string> };
