// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type ToolRequestType = { "kind": "ModifyFile", file_path: string, before: string, after: string, } | { "kind": "RunCommand", command: string, working_directory: string, } | { "kind": "ReadFiles", file_paths: Array<string>, } | { "kind": "SearchTypes", language: string, workspace_root: string, type_name: string, } | { "kind": "GetTypeDocs", language: string, workspace_root: string, type_path: string, } | { "kind": "Other", args: JsonValue, };
