// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TydeServerConnectionStateValue } from "./TydeServerConnectionStateValue";

export type TydeServerConnectionState = { host_id: string, state: TydeServerConnectionStateValue, };
