// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DisconnectedReason } from "./DisconnectedReason";
import type { ReconnectingAttempt } from "./ReconnectingAttempt";
import type { TydeServerConnectionScalarState } from "./TydeServerConnectionScalarState";

export type TydeServerConnectionStateValue = TydeServerConnectionScalarState | { reconnecting: ReconnectingAttempt, } | { disconnected: DisconnectedReason, };
