// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TydeServerVersionWarning = { host_id: string, host: string, local_version: string, remote_version: string, };
