// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionSettingsData } from "./SessionSettingsData";

export type UpdateSettingsParams = { conversationId: string, settings: SessionSettingsData, persist?: boolean, };
