// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateProjectRootsParams = { id: string, roots: Array<string>, host?: string, };
