// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkflowActionEntry = { "type": "run_command", command: string, } | { "type": "spawn_agent", prompt: string, name: string, } | { "type": "run_workflow", workflowId: string, };
