// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowActionEntry } from "./WorkflowActionEntry";

export type WorkflowStepEntry = { name: string, actions: Array<WorkflowActionEntry>, };
