// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowScope } from "./WorkflowScope";
import type { WorkflowStepEntry } from "./WorkflowStepEntry";

export type WorkflowEntry = { id: string, name: string, description: string, trigger: string, steps: Array<WorkflowStepEntry>, scope: WorkflowScope, };
