[package]
name = "devtools-protocol"
edition.workspace = true

[features]
default = ["launcher"]
launcher = ["dep:schemars", "dep:url"]

[dependencies]
schemars = { version = "1.2.1", optional = true }
serde.workspace = true
serde_json.workspace = true
url = { version = "2", optional = true }

[dev-dependencies]
tempfile = "3"
