[package]
name = "protocol"
edition.workspace = true

[features]
default = ["framing"]
framing = ["dep:tokio", "dep:tyde-time"]

[dependencies]
tyde-time = { path = "../time", optional = true }
host-config = { path = "../host-config" }
schemars = "1.2.1"
serde.workspace = true
serde_json.workspace = true
crc32fast = "1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1", optional = true, default-features = false, features = ["io-util", "time"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
tokio = { version = "1", optional = true, default-features = false, features = ["io-util"] }
