//! Optionally compiles the mobile web bundle into the binary.
//!
//! Direct hosting needs a built mobile web bundle to serve. Pointing every
//! install at a directory it has to assemble itself is a poor deal for the
//! deployment this exists for — a server dropped onto a work machine behind an
//! internal proxy — so a build that sets `TYDE_MOBILE_BUNDLE_DIR` bakes the
//! bundle in and needs no directory at all.
//!
//! A plain `cargo build` sets nothing and embeds nothing: the table below comes
//! out empty and hosts configure a directory as before. Release builds run
//! `tools/build-mobile-web-bundle.sh` first and point this at its output.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

/// Ceiling on what a build may bake in, mirroring the runtime limits in
/// `mobile_http.rs`. A path pointing at the wrong tree fails the build here
/// rather than producing a binary nobody can explain the size of.
const MAX_EMBEDDED_FILES: usize = 4096;
const MAX_EMBEDDED_BYTES: u64 = 128 * 1024 * 1024;

fn main() {
    println!("cargo::rerun-if-env-changed=TYDE_MOBILE_BUNDLE_DIR");

    let out_dir = PathBuf::from(std::env::var_os("OUT_DIR").expect("cargo sets OUT_DIR"));
    let dest = out_dir.join("embedded_mobile_web.rs");

    let mut generated = String::from(
        "// @generated by server/build.rs — do not edit.\n\
         /// Mobile web assets compiled into this binary, keyed by their path\n\
         /// relative to the bundle root. Empty unless the build set\n\
         /// `TYDE_MOBILE_BUNDLE_DIR`.\n\
         pub(crate) static EMBEDDED_MOBILE_WEB: &[(&str, &[u8])] = &[\n",
    );

    if let Some(root) = bundle_root() {
        let mut files = Vec::new();
        let mut total_bytes = 0u64;
        collect(&root, &root, &mut files, &mut total_bytes);
        files.sort();

        // The loader shell and the manifest it boots from are what make this a
        // servable bundle rather than an arbitrary directory. Missing either
        // means the path is wrong, and a build that bakes in the wrong tree is
        // worse than one that stops.
        for required in ["index.html", "manifest.json"] {
            if !files.iter().any(|(key, _)| key == required) {
                panic!(
                    "TYDE_MOBILE_BUNDLE_DIR={} has no {required}; point it at the output of \
                     tools/build-mobile-web-bundle.sh",
                    root.display()
                );
            }
        }

        for (key, path) in &files {
            println!("cargo::rerun-if-changed={}", path.display());
            let path = path
                .to_str()
                .unwrap_or_else(|| panic!("mobile bundle path is not UTF-8: {}", path.display()));
            writeln!(generated, "    ({key:?}, include_bytes!({path:?})),")
                .expect("writing to a String cannot fail");
        }
        println!(
            "cargo:warning=embedding {} mobile web files ({total_bytes} bytes) from {}",
            files.len(),
            root.display()
        );
    }

    generated.push_str("];\n");
    std::fs::write(&dest, generated)
        .unwrap_or_else(|err| panic!("failed to write {}: {err}", dest.display()));
}

fn bundle_root() -> Option<PathBuf> {
    let raw = std::env::var_os("TYDE_MOBILE_BUNDLE_DIR")?;
    if raw.is_empty() {
        return None;
    }
    let root = PathBuf::from(&raw);
    // `include_bytes!` resolves relative to the including source file, so the
    // generated table has to carry absolute paths.
    let root = std::fs::canonicalize(&root).unwrap_or_else(|err| {
        panic!(
            "TYDE_MOBILE_BUNDLE_DIR={} cannot be read: {err}",
            root.display()
        )
    });
    if !root.is_dir() {
        panic!(
            "TYDE_MOBILE_BUNDLE_DIR={} is not a directory",
            root.display()
        );
    }
    println!("cargo::rerun-if-changed={}", root.display());
    Some(root)
}

fn collect(root: &Path, dir: &Path, files: &mut Vec<(String, PathBuf)>, total_bytes: &mut u64) {
    let entries = std::fs::read_dir(dir)
        .unwrap_or_else(|err| panic!("failed to read {}: {err}", dir.display()));
    for entry in entries {
        let entry = entry.unwrap_or_else(|err| panic!("failed to read {}: {err}", dir.display()));
        let name = entry.file_name();
        let name = name.to_string_lossy();
        // Build droppings, skipped for the same reason the runtime loader and
        // web/deploy/generate-manifest.mjs skip them.
        if name.starts_with("._") || name == ".stage" {
            continue;
        }
        let path = entry.path();
        let file_type = entry
            .file_type()
            .unwrap_or_else(|err| panic!("failed to stat {}: {err}", path.display()));
        if file_type.is_dir() {
            println!("cargo::rerun-if-changed={}", path.display());
            collect(root, &path, files, total_bytes);
            continue;
        }
        if !file_type.is_file() {
            continue;
        }

        *total_bytes += entry
            .metadata()
            .unwrap_or_else(|err| panic!("failed to stat {}: {err}", path.display()))
            .len();
        if *total_bytes > MAX_EMBEDDED_BYTES || files.len() >= MAX_EMBEDDED_FILES {
            panic!(
                "TYDE_MOBILE_BUNDLE_DIR={} is larger than a bundle can be \
                 ({MAX_EMBEDDED_FILES} files / {MAX_EMBEDDED_BYTES} bytes)",
                root.display()
            );
        }

        let key = path
            .strip_prefix(root)
            .unwrap_or_else(|_| panic!("{} escaped {}", path.display(), root.display()))
            .components()
            .map(|component| component.as_os_str().to_string_lossy())
            .collect::<Vec<_>>()
            .join("/");
        files.push((key, path));
    }
}
