#[cfg(feature = "framing")]
pub mod framing;
pub mod types;
pub mod validator;

#[cfg(feature = "framing")]
pub use framing::{FrameError, read_envelope, write_envelope};
pub use types::{
    AgentBootstrapEvent, AgentBootstrapPayload, AgentClosedPayload, AgentControlStatus,
    AgentErrorCode, AgentErrorPayload, AgentId, AgentInput, AgentOrigin, AgentRenamedPayload,
    AgentStartPayload, AskUserQuestion, AskUserQuestionOption, BackendAccessMode, BackendKind,
    BackendSetupAction, BackendSetupCommand, BackendSetupInfo, BackendSetupPayload,
    BackendSetupStatus, BackendTierConfig, BrokerUrl, BrowseBootstrapListing,
    BrowseBootstrapPayload, CancelQueuedMessagePayload, ChatEvent, ChatMessage, ChatMessageId,
    ClientErrorCode, ClientErrorPayload, CloseAgentPayload, CommandErrorCode, CommandErrorPayload,
    ContextBreakdown, CustomAgent, CustomAgentDeletePayload, CustomAgentId,
    CustomAgentNotifyPayload, CustomAgentUpsertPayload, DEFAULT_MOBILE_MQTT_BROKER_URL,
    DeleteSessionPayload, DiffContextMode, EditQueuedMessagePayload, Envelope,
    ExitPlanModeDecision, FileEntryOp, FileInfo, FrameKind, GitBranchName, HelloPayload,
    HostAbsPath, HostBootstrapPayload, HostBrowseClosePayload, HostBrowseEntriesPayload,
    HostBrowseEntry, HostBrowseEntryError, HostBrowseErrorCode, HostBrowseErrorPayload,
    HostBrowseInitial, HostBrowseListPayload, HostBrowseOpenedPayload, HostBrowseStartPayload,
    HostPlatform, HostSettingValue, HostSettings, HostSettingsPayload, ImageData, InterruptPayload,
    ListSessionsPayload, McpServerConfig, McpServerDeletePayload, McpServerId,
    McpServerNotifyPayload, McpServerUpsertPayload, McpTransportConfig, MessageMetadataUpdateData,
    MessageOrigin, MessageSender, MobileAccessErrorCode, MobileAccessStatePayload,
    MobileBrokerStatus, MobileDeviceId, MobileDeviceRenamePayload, MobileDeviceRevokePayload,
    MobileDeviceState, MobileDeviceSummary, MobilePairingCancelPayload, MobilePairingOfferId,
    MobilePairingOfferPayload, MobilePairingQrUri, MobilePairingStartPayload, MobilePairingState,
    ModelInfo, NewAgentPayload, NewTerminalPayload, OperationCancelledData, PROTOCOL_VERSION,
    Project, ProjectAddRootPayload, ProjectBootstrapPayload, ProjectCreatePayload,
    ProjectDeletePayload, ProjectDeleteRootPayload, ProjectDiffScope, ProjectDiscardFilePayload,
    ProjectEventPayload, ProjectFileContentsPayload, ProjectFileEntry, ProjectFileKind,
    ProjectFileListPayload, ProjectGitChangeKind, ProjectGitCommitPayload,
    ProjectGitCommitResultPayload, ProjectGitDiffFile, ProjectGitDiffHunk, ProjectGitDiffLine,
    ProjectGitDiffLineKind, ProjectGitDiffPayload, ProjectGitFileStatus, ProjectGitStatusPayload,
    ProjectId, ProjectListDirPayload, ProjectNotifyPayload, ProjectPath, ProjectReadDiffPayload,
    ProjectReadFilePayload, ProjectRenamePayload, ProjectReorderPayload, ProjectReorderScope,
    ProjectRootGitStatus, ProjectRootListing, ProjectRootPath, ProjectSearchCancelPayload,
    ProjectSearchCompletePayload, ProjectSearchFileResult, ProjectSearchMatch,
    ProjectSearchPayload, ProjectSearchResultsPayload, ProjectSource, ProjectStageFilePayload,
    ProjectStageHunkPayload, ProjectUnstageFilePayload, ProtocolTypeError, QueuedMessageEntry,
    QueuedMessageId, QueuedMessagesPayload, ReasoningData, RejectCode, RejectPayload,
    RetryAttemptData, Review, ReviewActionPayload, ReviewAiReviewerState, ReviewAiReviewerStatus,
    ReviewAnchor, ReviewAnchorStatus, ReviewBootstrapPayload, ReviewComment, ReviewCommentId,
    ReviewCommentSource, ReviewCreatePayload, ReviewDiffSelection, ReviewDiffSide, ReviewErrorCode,
    ReviewErrorContext, ReviewErrorPayload, ReviewEventPayload, ReviewFileCommentCount, ReviewId,
    ReviewLocation, ReviewSeverity, ReviewStatus, ReviewSubmitTarget, ReviewSubscribePayload,
    ReviewSuggestedComment, ReviewSuggestionId, ReviewSuggestionState, ReviewSummary,
    ReviewSummaryScope, RunBackendSetupPayload, SelectOption, SendMessagePayload,
    SendMessageToolResponse, SendQueuedMessageNowPayload, SeqMismatch, SeqValidator, SessionId,
    SessionListPayload, SessionSchemaEntry, SessionSchemasPayload, SessionSettingField,
    SessionSettingFieldType, SessionSettingValue, SessionSettingsPayload, SessionSettingsSchema,
    SessionSettingsValues, SessionSummary, SetAgentNamePayload, SetSessionSettingsPayload,
    SetSettingPayload, Skill, SkillId, SkillNotifyPayload, SkillRefreshPayload, SpawnAgentParams,
    SpawnAgentPayload, SpawnCostHint, Steering, SteeringDeletePayload, SteeringId,
    SteeringNotifyPayload, SteeringScope, SteeringUpsertPayload, StreamEndData, StreamPath,
    StreamStartData, StreamTextDeltaData, SubAgentProgress, TYDE_VERSION, Task, TaskList,
    TaskStatus, Team, TeamCompactNotifyPayload, TeamCompactPayload, TeamCompactStatus,
    TeamCreateFromDraftPayload, TeamCreatePayload, TeamDeletePayload, TeamDraft,
    TeamDraftApplyTemplatePayload, TeamDraftCommitPayload, TeamDraftCreatePayload,
    TeamDraftDiscardPayload, TeamDraftId, TeamDraftMember, TeamDraftMemberEdit, TeamDraftMemberId,
    TeamDraftNotifyPayload, TeamDraftShufflePayload, TeamDraftShuffleScope, TeamDraftUpdatePayload,
    TeamId, TeamMember, TeamMemberActivatePayload, TeamMemberBindingNotifyPayload,
    TeamMemberBindingPayload, TeamMemberCreatePayload, TeamMemberCreateSpec,
    TeamMemberDeletePayload, TeamMemberId, TeamMemberNotifyPayload, TeamMemberPresetProfile,
    TeamMemberRole, TeamMemberShufflePayload, TeamMemberShuffleSuggestion,
    TeamMemberShuffleSuggestionNotifyPayload, TeamMemberState, TeamMemberUpdatePayload,
    TeamNotifyPayload, TeamPersonalityPreset, TeamPersonalityPresetId, TeamPersonalityTrait,
    TeamPersonalityTraitPreset, TeamPresetCatalog, TeamPresetCatalogNotifyPayload,
    TeamRenamePayload, TeamRolePreset, TeamRolePresetId, TeamSetManagerPayload, TeamTemplate,
    TeamTemplateId, TeamTemplateMember, TerminalBootstrapPayload, TerminalClosePayload,
    TerminalCreatePayload, TerminalErrorCode, TerminalErrorPayload, TerminalExitPayload,
    TerminalId, TerminalLaunchTarget, TerminalOutputPayload, TerminalResizePayload,
    TerminalSendPayload, TerminalStartPayload, TokenUsage, ToolExecutionCompletedData,
    ToolExecutionResult, ToolPolicy, ToolProgressData, ToolProgressUpdate, ToolRequest,
    ToolRequestType, ToolUseData, Version, WelcomePayload, WorkbenchCreatePayload,
    WorkbenchRemovePayload, WorkbenchRoot, WorkflowAgentState, WorkflowAgentStatus,
    WorkflowRunState, WorkflowRunStatus,
};
pub use validator::{ObservedFrame, ProtocolValidator, ProtocolViolation};
