#[cfg(feature = "framing")]
pub mod framing;
pub mod types;
pub mod validator;

#[cfg(feature = "framing")]
pub use framing::{FrameError, read_envelope, write_envelope};
pub use types::{
    AGENT_CONTROL_DEFAULT_READ_LIMIT, AGENT_CONTROL_DEFAULT_READ_MAX_BYTES,
    AGENT_CONTROL_MAX_READ_LIMIT, AGENT_CONTROL_MAX_READ_MAX_BYTES, AgentControlCappedEvents,
    AgentControlLatestOutput, AgentControlOutputProjectionError, AgentControlReadDebugResult,
    agent_control_output_from_chat_event, agent_control_output_from_envelope,
    cap_agent_control_events,
};
pub use types::{
    AgentActivityStats, AgentActivityStatsPayload, AgentActivitySummary,
    AgentActivitySummaryPayload, AgentActivitySummaryStaleReason, AgentActivitySummaryState,
    AgentAnnotationTarget, AgentBootstrapEvent, AgentBootstrapPayload, AgentClosedPayload,
    AgentControlAgentRef, AgentControlOutput, AgentControlProgress, AgentControlProgressKind,
    AgentControlReadResult, AgentControlStatus, AgentErrorCode, AgentErrorPayload, AgentGroup,
    AgentGroupAssignment, AgentGroupId, AgentGroupMode, AgentGroupsSnapshot, AgentGroupsUpdate,
    AgentId, AgentInput, AgentListDensity, AgentManualTagAssignment, AgentManualTagDescriptor,
    AgentManualTagId, AgentOrderKey, AgentOrigin, AgentPinsSnapshot, AgentPinsUpdate,
    AgentProjectFilter, AgentRenamedPayload, AgentSortMode, AgentStartPayload, AgentStatusFilter,
    AgentSystemTagAssignment, AgentSystemTagDescriptor, AgentSystemTagId, AgentTagColor,
    AgentTagRef, AgentTagsSnapshot, AgentTagsUpdate, AgentWorkflowMetadata,
    AgentsSidebarPreferences, AgentsSidebarProjectVisibility, AgentsSmartViewsSnapshot,
    AgentsSmartViewsUpdate, AgentsViewFilters, AgentsViewPreferences,
    AgentsViewPreferencesNotifyPayload, AgentsViewPreferencesSnapshot,
    AgentsViewPreferencesStoreError, AgentsViewPreferencesStoreErrorKind,
    AgentsViewPreferencesUpdate, AskUserQuestion, AskUserQuestionOption, BackendAccessMode,
    BackendConfigField, BackendConfigFieldType, BackendConfigPersistenceMode, BackendConfigSchema,
    BackendConfigSchemasPayload, BackendConfigSnapshot, BackendConfigSnapshotStatus,
    BackendConfigSnapshotsPayload, BackendConfigValues, BackendKind, BackendNativeSettingsGroup,
    BackendNativeSettingsGroupKind, BackendNativeSettingsSnapshot, BackendSetupAction,
    BackendSetupCommand, BackendSetupDiagnostic, BackendSetupDiagnosticCode, BackendSetupInfo,
    BackendSetupPayload, BackendSetupStatus, BackendTierConfig, BackgroundAgentFeature,
    BackgroundAgentFeaturesSettings, BrokerUrl, BrowseBootstrapListing, BrowseBootstrapPayload,
    BuiltInSmartViewId, ByteRange, CancelQueuedMessagePayload, CancelWorkflowPayload, ChatEvent,
    ChatMessage, ChatMessageId, ClientErrorCode, ClientErrorPayload, CloseAgentPayload,
    CodeIntelCancelReferencesPayload, CodeIntelCompleteness, CodeIntelDiagnostic,
    CodeIntelDiagnosticsPayload, CodeIntelErrorCode, CodeIntelErrorContext, CodeIntelErrorPayload,
    CodeIntelFileModelPayload, CodeIntelFindReferencesPayload, CodeIntelHoverPayload,
    CodeIntelHoverResultPayload, CodeIntelLanguageId, CodeIntelLocation, CodeIntelModelRange,
    CodeIntelNavigatePayload, CodeIntelNavigateResultPayload, CodeIntelOccurrence,
    CodeIntelOverviewHeadline, CodeIntelOverviewPayload, CodeIntelOverviewSummary,
    CodeIntelProviderId, CodeIntelProviderStatus, CodeIntelReferenceLine,
    CodeIntelReferencesCompletePayload, CodeIntelReferencesFileResult,
    CodeIntelReferencesResultsPayload, CodeIntelResourceMode, CodeIntelRole, CodeIntelRootOverview,
    CodeIntelSetVisibleRangePayload, CodeIntelSettings, CodeIntelSeverity, CodeIntelState,
    CodeIntelStatusPayload, CodeIntelStatusScope, CodeIntelSubscribeFilePayload,
    CodeIntelUnsubscribeFilePayload, CommandErrorCode, CommandErrorPayload, ContextBreakdown,
    CustomAgent, CustomAgentDeletePayload, CustomAgentId, CustomAgentNotifyPayload,
    CustomAgentUpsertPayload, DEFAULT_MOBILE_MQTT_BROKER_URL,
    DEFAULT_MOBILE_SESSION_LIST_PAGE_LIMIT, DEFAULT_SESSION_LIST_PAGE_LIMIT, DeleteSessionPayload,
    DiffContextMode, EditQueuedMessagePayload, Envelope, ExitPlanModeDecision,
    FetchSessionHistoryPayload, FileEntryOp, FileInfo, FrameKind, GitBranchName, HelloPayload,
    HostAbsPath, HostBootstrapPayload, HostBrowseClosePayload, HostBrowseEntriesPayload,
    HostBrowseEntry, HostBrowseEntryError, HostBrowseErrorCode, HostBrowseErrorPayload,
    HostBrowseInitial, HostBrowseListPayload, HostBrowseOpenedPayload, HostBrowseStartPayload,
    HostExecutablePath, HostFilterId, HostLaunchProfileConfig, HostPlatform, HostSettingValue,
    HostSettings, HostSettingsPayload, ImageData, InterruptPayload, LaunchProfile,
    LaunchProfileCatalog, LaunchProfileCatalogPayload, LaunchProfileEntry, LaunchProfileId,
    LaunchProfileKind, ListSessionsPayload, LoadAgentPayload, MAX_SESSION_LIST_PAGE_LIMIT,
    ManagedBrokerAuthorizerName, ManagedBrokerClientId, ManagedBrokerConnectAuth,
    ManagedBrokerCredentialScope, ManagedBrokerCredentials, ManagedBrokerEndpoint,
    ManagedBrokerGrantId, ManagedBrokerProvider, ManagedBrokerRegion, ManagedBrokerRole,
    ManagedBrokerTopicNamespace, McpServerConfig, McpServerDeletePayload, McpServerId,
    McpServerNotifyPayload, McpServerUpsertPayload, McpTransportConfig, MessageMetadataUpdateData,
    MessageOrigin, MessageSender, MessageTokenUsage, MobileAccessErrorCode,
    MobileAccessStatePayload, MobileBrokerStatus, MobileDeviceId, MobileDeviceRenamePayload,
    MobileDeviceRevokePayload, MobileDeviceState, MobileDeviceSummary, MobilePairingCancelPayload,
    MobilePairingOfferId, MobilePairingOfferPayload, MobilePairingQrUri, MobilePairingStartPayload,
    MobilePairingState, MobileServiceAuthState, MobileServiceAuthStatePayload, ModelInfo,
    ModelRequestId, ModelRequestTokenUsage, ModelTurnId, NewAgentPayload, NewTerminalPayload,
    OperationCancelledData, OrchestrationAgentOrigin, OrchestrationAgentType,
    OrchestrationCandidateInfo, OrchestrationEvent, OrchestrationId, OrchestrationOutcomeStatus,
    OrchestrationPanelPosition, OrchestrationPanelVerdict, OrchestrationPayload,
    OrchestrationReviewVerdict, OrchestrationWorkerInfo, OrchestrationWorkflowPhase,
    PROTOCOL_VERSION, Project, ProjectAccessedPayload, ProjectAddRootPayload,
    ProjectBootstrapPayload, ProjectCreatePayload, ProjectDeletePayload, ProjectDeleteRootPayload,
    ProjectDiffScope, ProjectDiscardFilePayload, ProjectEventPayload, ProjectFileContentsPayload,
    ProjectFileEntry, ProjectFileKind, ProjectFileListPayload, ProjectFileVersion,
    ProjectFileVersionChange, ProjectGitChangeKind, ProjectGitCommitPayload,
    ProjectGitCommitResultPayload, ProjectGitDiffFile, ProjectGitDiffHunk, ProjectGitDiffLine,
    ProjectGitDiffLineKind, ProjectGitDiffPayload, ProjectGitFileStatus, ProjectGitStatusPayload,
    ProjectId, ProjectListDirPayload, ProjectNotifyPayload, ProjectPath, ProjectReadDiffPayload,
    ProjectReadFilePayload, ProjectRenamePayload, ProjectReorderPayload, ProjectReorderScope,
    ProjectRootGitStatus, ProjectRootListing, ProjectRootPath, ProjectSearchCancelPayload,
    ProjectSearchCompletePayload, ProjectSearchFileResult, ProjectSearchMatch,
    ProjectSearchPayload, ProjectSearchResultsPayload, ProjectSource, ProjectStageFilePayload,
    ProjectStageHunkPayload, ProjectUnstageFilePayload, ProtocolTypeError, QueuedMessageEntry,
    QueuedMessageId, QueuedMessagesPayload, ReasoningData, RejectCode, RejectPayload,
    RetryAttemptData, Review, ReviewActionPayload, ReviewAiReviewerState, ReviewAiReviewerStatus,
    ReviewAnchor, ReviewAnchorStatus, ReviewBootstrapPayload, ReviewComment, ReviewCommentId,
    ReviewCommentSource, ReviewCreatePayload, ReviewDiffSelection, ReviewDiffSide, ReviewErrorCode,
    ReviewErrorContext, ReviewErrorPayload, ReviewEventPayload, ReviewFileCommentCount, ReviewId,
    ReviewLocation, ReviewSeverity, ReviewStatus, ReviewSubmitTarget, ReviewSubscribePayload,
    ReviewSuggestedComment, ReviewSuggestionId, ReviewSuggestionState, ReviewSummary,
    ReviewSummaryScope, RunBackendSetupPayload, SelectOption, SelectOptionsBySetting,
    SelectOptionsForValue, SendMessagePayload, SendMessageToolResponse,
    SendQueuedMessageNowPayload, SeqMismatch, SeqValidator, SessionHistoryPayload, SessionId,
    SessionListCursor, SessionListGeneration, SessionListPageInfo, SessionListPageStatus,
    SessionListPayload, SessionListScope, SessionSchemaEntry, SessionSchemasPayload,
    SessionSettingField, SessionSettingFieldType, SessionSettingValue, SessionSettingsPayload,
    SessionSettingsSchema, SessionSettingsValues, SessionSummary, SetAgentGroupsPayload,
    SetAgentNamePayload, SetAgentPinsPayload, SetAgentTagsPayload, SetAgentsSmartViewsPayload,
    SetAgentsViewPreferencesPayload, SetSessionSettingsPayload, SetSettingPayload, Skill, SkillId,
    SkillNotifyPayload, SkillRefreshPayload, SmartView, SmartViewId, SpawnAgentParams,
    SpawnAgentPayload, SpawnCostHint, Steering, SteeringDeletePayload, SteeringId,
    SteeringNotifyPayload, SteeringScope, SteeringUpsertPayload, StreamEndData, StreamPath,
    StreamStartData, StreamTextDeltaData, SubAgentProgress, TYDE_VERSION, Task, TaskList,
    TaskStatus, TaskTokenUsageAggregate, TaskTokenUsageAmount, TaskTokenUsageEntry,
    TaskTokenUsagePayload, TaskTokenUsageScope, TaskTokenUsageStatus,
    TaskTokenUsageUnavailableReason, Team, TeamCompactNotifyPayload, TeamCompactPayload,
    TeamCompactStatus, TeamCreateFromDraftPayload, TeamCreatePayload, TeamDeletePayload, TeamDraft,
    TeamDraftApplyTemplatePayload, TeamDraftCommitPayload, TeamDraftCreatePayload,
    TeamDraftDiscardPayload, TeamDraftId, TeamDraftMember, TeamDraftMemberEdit, TeamDraftMemberId,
    TeamDraftNotifyPayload, TeamDraftShufflePayload, TeamDraftShuffleScope, TeamDraftUpdatePayload,
    TeamId, TeamMember, TeamMemberActivatePayload, TeamMemberBindingNotifyPayload,
    TeamMemberBindingPayload, TeamMemberCreatePayload, TeamMemberCreateSpec,
    TeamMemberDeletePayload, TeamMemberId, TeamMemberNotifyPayload, TeamMemberPresetProfile,
    TeamMemberRole, TeamMemberShufflePayload, TeamMemberShuffleSuggestion,
    TeamMemberShuffleSuggestionNotifyPayload, TeamMemberState, TeamMemberUpdatePayload,
    TeamNotifyPayload, TeamPersonalityPreset, TeamPersonalityPresetId, TeamPersonalityTrait,
    TeamPersonalityTraitPreset, TeamPresetCatalog, TeamPresetCatalogNotifyPayload,
    TeamRenamePayload, TeamRolePreset, TeamRolePresetId, TeamSetManagerPayload, TeamTemplate,
    TeamTemplateId, TeamTemplateMember, TerminalBootstrapPayload, TerminalClosePayload,
    TerminalCreatePayload, TerminalErrorCode, TerminalErrorPayload, TerminalExitPayload,
    TerminalId, TerminalLaunchTarget, TerminalOutputPayload, TerminalResizePayload,
    TerminalSendPayload, TerminalStartPayload, TokenUsage, TokenUsageScope,
    TokenUsageUnavailableReason, ToolExecutionCompletedData, ToolExecutionResult, ToolPolicy,
    ToolProgressData, ToolProgressUpdate, ToolRequest, ToolRequestType, ToolUseData,
    TriggerSurface, TriggerWorkflowPayload, TycodeModel, UserSmartViewId, Version, WelcomePayload,
    WorkbenchCreatePayload, WorkbenchRemovePayload, WorkbenchRoot, WorkflowAgentState,
    WorkflowAgentStatus, WorkflowCatalogLocation, WorkflowCoordinatorSpec, WorkflowDiagnostic,
    WorkflowDiagnosticSeverity, WorkflowId, WorkflowInputControl, WorkflowInputOption,
    WorkflowInputSpec, WorkflowNotifyPayload, WorkflowRefreshPayload, WorkflowRunId,
    WorkflowRunNotifyPayload, WorkflowRunSnapshot, WorkflowRunSnapshotStatus, WorkflowRunState,
    WorkflowRunStatus, WorkflowSaveMode, WorkflowSaveRequest, WorkflowSaveResponse,
    WorkflowSaveTarget, WorkflowSource, WorkflowSourceScope, WorkflowStepRunId,
    WorkflowStepRunSnapshot, WorkflowStepRunSnapshotStatus, WorkflowSummary,
    WorkflowTargetDirectory, WorkflowTargetsResponse,
};
// Re-exported from host-config via types.rs; the bundle-key type for the
// web/PWA client (see WelcomePayload::release_version).
pub use types::{LOCAL_HOST_ID, TydeReleaseVersion};
pub use validator::{ObservedFrame, ProtocolValidator, ProtocolViolation};
