#[cfg(feature = "framing")]
pub mod framing;
pub mod hermes_config;
pub mod types;
pub mod validator;

#[cfg(feature = "framing")]
pub use framing::{
    EncodedRecord, FrameError, FrameReader, ProtocolFrame, RECORD_MAGIC, RECORD_VERSION,
    encode_frame, read_envelope, write_envelope, write_frame,
};
pub use types::{
    AGENT_CONTROL_DEFAULT_READ_LIMIT, AGENT_CONTROL_DEFAULT_READ_MAX_BYTES,
    AGENT_CONTROL_MAX_READ_LIMIT, AGENT_CONTROL_MAX_READ_MAX_BYTES, AgentControlCappedEvents,
    AgentControlLatestOutput, AgentControlOutputProjectionError, AgentControlReadDebugResult,
    agent_control_output_from_chat_event, agent_control_output_from_envelope,
    cap_agent_control_events,
};
pub use types::{
    AcpAdapterId, AcpAgentSpec, AgentActivityStats, AgentActivityStatsPayload,
    AgentActivitySummary, AgentActivitySummaryPayload, AgentActivitySummaryStaleReason,
    AgentActivitySummaryState, AgentAnnotationTarget, AgentBootstrapEvent, AgentBootstrapPayload,
    AgentClosedPayload, AgentCompactNotifyPayload, AgentCompactPayload, AgentCompactStatus,
    AgentControlAgentRef, AgentControlOutput, AgentControlProgress, AgentControlProgressKind,
    AgentControlProgressStatus, AgentControlReadResult, AgentControlStatus, AgentErrorCode,
    AgentErrorPayload, AgentExecutionMode, AgentGroup, AgentGroupAssignment, AgentGroupId,
    AgentGroupMode, AgentGroupsSnapshot, AgentGroupsUpdate, AgentId, AgentInput, AgentListDensity,
    AgentManualTagAssignment, AgentManualTagDescriptor, AgentManualTagId, AgentOrderKey,
    AgentOrigin, AgentPinsSnapshot, AgentPinsUpdate, AgentProjectFilter, AgentRenamedPayload,
    AgentSortMode, AgentStartPayload, AgentStatusFilter, AgentSystemTagAssignment,
    AgentSystemTagDescriptor, AgentSystemTagId, AgentTagColor, AgentTagRef, AgentTagsSnapshot,
    AgentTagsUpdate, AgentTurnStateNotifyPayload, AgentWorkflowMetadata, AgentsSidebarPreferences,
    AgentsSidebarProjectVisibility, AgentsSmartViewsSnapshot, AgentsSmartViewsUpdate,
    AgentsViewFilters, AgentsViewPreferences, AgentsViewPreferencesNotifyPayload,
    AgentsViewPreferencesSnapshot, AgentsViewPreferencesStoreError,
    AgentsViewPreferencesStoreErrorKind, AgentsViewPreferencesUpdate, AskUserQuestion,
    AskUserQuestionOption, BackendAccessMode, BackendCapacityPayload, BackendCapacitySnapshot,
    BackendCapacityState, BackendConfigField, BackendConfigFieldType, BackendConfigPersistenceMode,
    BackendConfigSchema, BackendConfigSchemasPayload, BackendConfigSnapshot,
    BackendConfigSnapshotStatus, BackendConfigSnapshotsPayload, BackendConfigValues, BackendKind,
    BackendNativeSettingsAdvisory, BackendNativeSettingsGroup, BackendNativeSettingsGroupKind,
    BackendNativeSettingsSnapshot, BackendNativeSettingsWritePayload,
    BackendSettingsRefreshPayload, BackendSetupAction, BackendSetupCommand, BackendSetupDiagnostic,
    BackendSetupDiagnosticCode, BackendSetupInfo, BackendSetupPayload, BackendSetupStatus,
    BrokerUrl, BrowseBootstrapListing, BrowseBootstrapPayload, BuiltInSmartViewId, ByteRange,
    CancelBackgroundTaskPayload, CancelQueuedMessagePayload, CancelWorkflowPayload, CapacityBucket,
    CapacityBucketId, CapacityBucketStatus, CapacityCoverage, CapacityErrorCode,
    CapacityErrorDetail, CapacityFreshness, CapacityMeasure, CapacityPlanLabel, CapacityReport,
    CapacityReset, CapacityScope, CapacitySource, CapacityUnavailableReason,
    CapacityUnsupportedReason, CapacityWindow, ChatEvent, ChatMessage, ChatMessageId,
    ClaudeLimitType, ClientErrorCode, ClientErrorPayload, CloseAgentPayload,
    CodeIntelCancelReferencesPayload, CodeIntelCompleteness, CodeIntelDiagnostic,
    CodeIntelDiagnosticsPayload, CodeIntelErrorCode, CodeIntelErrorContext, CodeIntelErrorPayload,
    CodeIntelFileModelPayload, CodeIntelFindReferencesPayload, CodeIntelHoverPayload,
    CodeIntelHoverResultPayload, CodeIntelLanguageId, CodeIntelLocation, CodeIntelModelRange,
    CodeIntelNavigatePayload, CodeIntelNavigateResultPayload, CodeIntelOccurrence,
    CodeIntelOverviewHeadline, CodeIntelOverviewPayload, CodeIntelOverviewSummary,
    CodeIntelProviderId, CodeIntelProviderStatus, CodeIntelReferenceLine,
    CodeIntelReferencesCompletePayload, CodeIntelReferencesFileResult,
    CodeIntelReferencesResultsPayload, CodeIntelResourceMode, CodeIntelRole, CodeIntelRootOverview,
    CodeIntelSetVisibleRangePayload, CodeIntelSeverity, CodeIntelState, CodeIntelStatusPayload,
    CodeIntelStatusScope, CodeIntelSubscribeFilePayload, CodeIntelUnsubscribeFilePayload,
    CodexLimitSlot, CommandErrorCode, CommandErrorPayload, CompactionAvailabilityReason,
    CompactionMethod, CompactionMetrics, CompactionMutation, CompactionObservationId,
    CompactionOperationId, CompactionStage, CompactionTrigger, ConfiguredSecret, ContextBreakdown,
    ContextCompactionCapabilityPayload, ContextCompactionNotifyPayload, ContextCompactionStatus,
    ContextCompactionTimelineEvent, ContextCompactionTimelineStatus, CurrentContextUsage,
    CustomAgent, CustomAgentDeletePayload, CustomAgentId, CustomAgentNotifyPayload,
    CustomAgentUpsertPayload, DEFAULT_MOBILE_MQTT_BROKER_URL,
    DEFAULT_MOBILE_SESSION_LIST_PAGE_LIMIT, DEFAULT_SESSION_LIST_PAGE_LIMIT, DeleteSessionPayload,
    DiffContextMode, EditQueuedMessagePayload, Envelope, ExitPlanModeDecision,
    FetchSessionHistoryPayload, FileEntryOp, FileInfo, FrameKind, GitBranchName, HeartbeatPayload,
    HelloPayload, HistoryPageRequestId, HostAbsPath, HostBootstrapPayload, HostBrowseClosePayload,
    HostBrowseEntriesPayload, HostBrowseEntry, HostBrowseEntryError, HostBrowseErrorCode,
    HostBrowseErrorPayload, HostBrowseInitial, HostBrowseListPayload, HostBrowseOpenedPayload,
    HostBrowseStartPayload, HostFilterId, HostPlatform, HostSettingsPayload, ImageData,
    InterruptPayload, InvokeSettingsActionPayload, LaunchProfile, LaunchProfileCatalog,
    LaunchProfileCatalogPayload, LaunchProfileEntry, LaunchProfileId, LaunchProfileKind,
    ListSessionsPayload, LoadAgentPayload, MAX_SESSION_LIST_PAGE_LIMIT,
    ManagedBrokerAuthorizerName, ManagedBrokerClientId, ManagedBrokerConnectAuth,
    ManagedBrokerCredentialScope, ManagedBrokerCredentials, ManagedBrokerEndpoint,
    ManagedBrokerGrantId, ManagedBrokerProvider, ManagedBrokerRegion, ManagedBrokerRole,
    ManagedBrokerTopicNamespace, McpServerConfig, McpServerDeletePayload, McpServerId,
    McpServerNotifyPayload, McpServerUpsertPayload, McpTransportConfig, MessageMetadataUpdateData,
    MessageOrigin, MessageSender, MessageTokenUsage, MobileAccessErrorCode,
    MobileAccessStatePayload, MobileBrokerStatus, MobileDeviceId, MobileDeviceRenamePayload,
    MobileDeviceRevokePayload, MobileDeviceState, MobileDeviceSummary, MobileDeviceToken,
    MobileDirectErrorResponse, MobileDirectHostingStatus, MobileDirectPairRequest,
    MobileDirectPairResponse, MobilePairingCancelPayload, MobilePairingOfferId,
    MobilePairingOfferPayload, MobilePairingQrUri, MobilePairingStartPayload, MobilePairingState,
    MobilePushNotification, MobilePushReason, MobilePushState, MobilePushSubscribePayload,
    MobilePushSubscription, MobilePushUnsubscribePayload, MobileServiceAuthState,
    MobileServiceAuthStatePayload, MobileWebBundleSource, ModelInfo, ModelRequestId,
    ModelRequestTokenUsage, ModelTurnId, NewAgentPayload, NewTerminalPayload,
    OperationCancelledData, OrchestrationAgentOrigin, OrchestrationAgentType,
    OrchestrationCandidateInfo, OrchestrationEvent, OrchestrationId, OrchestrationOutcomeStatus,
    OrchestrationPanelPosition, OrchestrationPanelVerdict, OrchestrationPayload,
    OrchestrationReviewVerdict, OrchestrationWorkerInfo, OrchestrationWorkflowPhase,
    PROTOCOL_VERSION, PercentValueProvenance, Project, ProjectAccessedPayload,
    ProjectAddRootPayload, ProjectBootstrapPayload, ProjectCreatePayload, ProjectDeletePayload,
    ProjectDeleteRootPayload, ProjectDiffRevision, ProjectDiffScope, ProjectDiscardFilePayload,
    ProjectEventPayload, ProjectFileContentsPayload, ProjectFileEntry, ProjectFileKind,
    ProjectFileListPayload, ProjectFileVersion, ProjectFileVersionChange, ProjectGitChangeKind,
    ProjectGitCommitPayload, ProjectGitCommitResultPayload, ProjectGitCommitSummary,
    ProjectGitDiffFile, ProjectGitDiffHunk, ProjectGitDiffLine, ProjectGitDiffLineKind,
    ProjectGitDiffPayload, ProjectGitFileStatus, ProjectGitStatusPayload, ProjectId,
    ProjectListDirPayload, ProjectNotifyPayload, ProjectPath, ProjectReadDiffPayload,
    ProjectReadFilePayload, ProjectRenamePayload, ProjectReorderPayload, ProjectReorderScope,
    ProjectRootGitStatus, ProjectRootListing, ProjectRootPath, ProjectSearchCancelPayload,
    ProjectSearchCompletePayload, ProjectSearchFileResult, ProjectSearchMatch,
    ProjectSearchPayload, ProjectSearchResultsPayload, ProjectSource, ProjectStageFilePayload,
    ProjectStageHunkPayload, ProjectUnstageFilePayload, ProtocolTypeError, PushAuthSecret,
    PushEndpointUrl, PushPublicKey, QueuedMessageEntry, QueuedMessageId, QueuedMessagesPayload,
    ReasoningData, RejectCode, RejectPayload, RequestedCompactionAvailability,
    RequestedCompactionRoute, RetryAttemptData, Review, ReviewActionPayload, ReviewAiReviewerState,
    ReviewAiReviewerStatus, ReviewAiScope, ReviewAnchor, ReviewAnchorStatus,
    ReviewBootstrapPayload, ReviewComment, ReviewCommentId, ReviewCommentSource,
    ReviewCreatePayload, ReviewDiffSelection, ReviewDiffSide, ReviewErrorCode, ReviewErrorContext,
    ReviewErrorPayload, ReviewEventPayload, ReviewFileCommentCount, ReviewFileSnapshot, ReviewId,
    ReviewLocation, ReviewSeverity, ReviewStatus, ReviewSubmitTarget, ReviewSubscribePayload,
    ReviewSuggestedComment, ReviewSuggestionId, ReviewSuggestionState, ReviewSummary,
    ReviewSummaryScope, ReviewTarget, RunBackendSetupPayload, SETTINGS_WRITE_MAX_OPS,
    SUPERVISOR_MESSAGE_PREFIX, SUPERVISOR_STALL_INTERRUPT_NOTICE_PREFIX, SelectOption,
    SelectOptionsBySetting, SelectOptionsForValue, SendMessagePayload, SendMessageToolResponse,
    SendQueuedMessageNowPayload, SeqMismatch, SeqValidator, SessionHistoryPayload, SessionId,
    SessionListCursor, SessionListGeneration, SessionListPageInfo, SessionListPageStatus,
    SessionListPayload, SessionListScope, SessionSchemaEntry, SessionSchemasPayload,
    SessionSettingField, SessionSettingFieldType, SessionSettingValue, SessionSettingsPayload,
    SessionSettingsSchema, SessionSettingsValues, SessionSummary,
    SessionSummaryCountUpdatedPayload, SetAgentGroupsPayload, SetAgentNamePayload,
    SetAgentPinsPayload, SetAgentTagsPayload, SetAgentsSmartViewsPayload,
    SetAgentsViewPreferencesPayload, SetSessionSettingsPayload, SettingExpectation, SettingOp,
    SettingsErrorCode, SettingsFieldError, SettingsWriteId, SettingsWritePayload,
    SettingsWriteResultPayload, Skill, SkillId, SkillNotifyPayload, SkillRefreshPayload, SmartView,
    SmartViewId, SpawnAgentParams, SpawnAgentPayload, SpawnCostHint, Steering,
    SteeringDeletePayload, SteeringId, SteeringNotifyPayload, SteeringScope, SteeringUpsertPayload,
    StreamEndData, StreamPath, StreamStartData, StreamTextDeltaData, SubAgentProgress,
    SubAgentProgressStatus, TYDE_VERSION, Task, TaskList, TaskStatus, TaskTokenUsageAggregate,
    TaskTokenUsageAmount, TaskTokenUsageEntry, TaskTokenUsagePayload, TaskTokenUsageScope,
    TaskTokenUsageStatus, TaskTokenUsageUnavailableReason, Team, TeamCompactNotifyPayload,
    TeamCompactPayload, TeamCompactStatus, TeamContextCompactionNotifyPayload,
    TeamContextCompactionStatus, TeamCreateFromDraftPayload, TeamCreatePayload, TeamDeletePayload,
    TeamDraft, TeamDraftApplyTemplatePayload, TeamDraftCommitPayload, TeamDraftCreatePayload,
    TeamDraftDiscardPayload, TeamDraftId, TeamDraftMember, TeamDraftMemberEdit, TeamDraftMemberId,
    TeamDraftNotifyPayload, TeamDraftShufflePayload, TeamDraftShuffleScope, TeamDraftUpdatePayload,
    TeamId, TeamMember, TeamMemberActivatePayload, TeamMemberBindingNotifyPayload,
    TeamMemberBindingPayload, TeamMemberContextCompactionResult, TeamMemberCreatePayload,
    TeamMemberCreateSpec, TeamMemberDeletePayload, TeamMemberId, TeamMemberNotifyPayload,
    TeamMemberPresetProfile, TeamMemberRole, TeamMemberShufflePayload, TeamMemberShuffleSuggestion,
    TeamMemberShuffleSuggestionNotifyPayload, TeamMemberState, TeamMemberUpdatePayload,
    TeamNotifyPayload, TeamPersonalityPreset, TeamPersonalityPresetId, TeamPersonalityTrait,
    TeamPersonalityTraitPreset, TeamPresetCatalog, TeamPresetCatalogNotifyPayload,
    TeamRenamePayload, TeamRolePreset, TeamRolePresetId, TeamSetManagerPayload, TeamTemplate,
    TeamTemplateId, TeamTemplateMember, TerminalBootstrapPayload, TerminalClosePayload,
    TerminalCreatePayload, TerminalErrorCode, TerminalErrorPayload, TerminalExitPayload,
    TerminalId, TerminalLaunchTarget, TerminalOutputPayload, TerminalResizePayload,
    TerminalSendPayload, TerminalStartPayload, TokenUsage, TokenUsageScope,
    TokenUsageUnavailableReason, ToolExecutionCompletedData, ToolExecutionMode,
    ToolExecutionNormalizationFailure, ToolExecutionOutcome, ToolExecutionResult, ToolPolicy,
    ToolProgressData, ToolProgressUpdate, ToolRequest, ToolRequestType, ToolUseData,
    TriggerSurface, TriggerWorkflowPayload, TycodeModel, TydeAgentWaitStatus, UserSmartViewId,
    ValueProvenance, VapidPrivateKey, VapidPublicKey, Version, WelcomePayload,
    WorkbenchCreatePayload, WorkbenchRemovePayload, WorkbenchRoot, WorkflowAgentState,
    WorkflowAgentStatus, WorkflowCatalogLocation, WorkflowCoordinatorSpec, WorkflowDiagnostic,
    WorkflowDiagnosticSeverity, WorkflowId, WorkflowInputControl, WorkflowInputOption,
    WorkflowInputSpec, WorkflowNotifyPayload, WorkflowRefreshPayload, WorkflowRunId,
    WorkflowRunNotifyPayload, WorkflowRunSnapshot, WorkflowRunSnapshotStatus, WorkflowRunState,
    WorkflowRunStatus, WorkflowSaveMode, WorkflowSaveRequest, WorkflowSaveResponse,
    WorkflowSaveTarget, WorkflowSource, WorkflowSourceScope, WorkflowStepRunId,
    WorkflowStepRunSnapshot, WorkflowStepRunSnapshotStatus, WorkflowSummary,
    WorkflowTargetDirectory, WorkflowTargetsResponse, parse_json_pointer,
};
pub use types::{
    BrowserAecStatus, MAX_VOICE_AUDIO_BYTES, MAX_VOICE_PACKETS_PER_FRAME, VOICE_PROTOCOL_VERSION,
    VOICE_SESSION_MAX_SECONDS, VoiceAcceptedPayload, VoiceAcceptedRequest, VoiceAudioCodec,
    VoiceAudioFormat, VoiceAudioPayload, VoiceAvailability, VoiceCapabilitiesPayload,
    VoiceDirection, VoiceErrorCode, VoiceErrorPayload, VoiceFlowStats, VoiceFormatPair, VoiceMode,
    VoiceRequest, VoiceSessionId, VoiceSessionPayload, VoiceSessionState, VoiceStartPayload,
    VoiceStatePayload, VoiceStopPayload, VoiceStopReason, VoiceTarget, VoiceTranscriptPayload,
    VoiceTranscriptSpeaker, VoiceUnavailableReason,
};
// Re-exported from host-config via types.rs; the bundle-key type for the
// web/PWA client (see WelcomePayload::release_version).
pub use types::{
    KIRO_BACKEND, KIRO_LAUNCH_PROFILE_ID, LEGACY_ACP_BACKEND, LEGACY_SIDE_QUESTION_ORIGIN,
    LOCAL_HOST_ID, TydeReleaseVersion,
};
pub use validator::{ObservedFrame, ProtocolValidator, ProtocolViolation};
