//! Web Push delivery: RFC 8188 `aes128gcm` content encoding, RFC 8291 key
//! derivation, and RFC 8292 VAPID authorization.
//!
//! The host encrypts under the subscription's own `p256dh`/`auth` keys, so the
//! push service (Apple, Google, Mozilla) relays a payload it cannot read; the
//! browser decrypts it and hands the plaintext to the service worker. The VAPID
//! key pair is generated by the device and shared with each paired host, which
//! is what lets one push subscription serve several hosts.

use aes_gcm::aead::{Aead, Payload};
use aes_gcm::{Aes128Gcm, Key, KeyInit, Nonce};
use base64::Engine;
use base64::engine::general_purpose::URL_SAFE_NO_PAD;
use hkdf::Hkdf;
use p256::ecdh::diffie_hellman;
use p256::ecdsa::signature::Signer;
use p256::ecdsa::{Signature, SigningKey};
use p256::elliptic_curve::rand_core::OsRng;
use p256::elliptic_curve::sec1::ToEncodedPoint;
use p256::{PublicKey, SecretKey};
use protocol::{MobilePushNotification, MobilePushSubscription};
use sha2::Sha256;

/// How long the push service should hold the message for a device that is
/// offline. An idle notification is worthless once stale, so this is short.
const PUSH_TTL_SECONDS: u32 = 600;
/// RFC 8292 caps `exp` at 24 hours out. Each message is signed fresh, so a
/// shorter window costs nothing.
const VAPID_TOKEN_LIFETIME_SECONDS: u64 = 12 * 60 * 60;
/// VAPID `sub` must identify the sender to the push service operator. It is a
/// product contact, deliberately not anything about the user.
const VAPID_SUBJECT: &str = "https://tycode.dev/";
/// Single-record message: larger than any notification we send, so the payload
/// never needs splitting.
const RECORD_SIZE: u32 = 4096;

#[derive(Debug)]
pub(crate) enum PushSendError {
    /// The stored subscription is not usable: malformed keys, or an endpoint
    /// that is not a valid absolute URL.
    InvalidSubscription(String),
    Encryption(String),
    Transport(String),
    /// The push service accepted the request shape but rejected the
    /// subscription as gone (404/410). The device must re-subscribe.
    SubscriptionGone,
    /// Any other non-success response from the push service.
    Rejected {
        status: u16,
        body: String,
    },
}

impl std::fmt::Display for PushSendError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::InvalidSubscription(detail) => {
                write!(formatter, "invalid push subscription: {detail}")
            }
            Self::Encryption(detail) => write!(formatter, "push encryption failed: {detail}"),
            Self::Transport(detail) => write!(formatter, "push transport failed: {detail}"),
            Self::SubscriptionGone => {
                formatter.write_str("push service reports the subscription is gone")
            }
            Self::Rejected { status, body } => {
                write!(
                    formatter,
                    "push service rejected delivery ({status}): {body}"
                )
            }
        }
    }
}

impl std::error::Error for PushSendError {}

/// Encrypts `notification` for `subscription` and POSTs it to the endpoint.
pub(crate) async fn send_push(
    client: &reqwest::Client,
    subscription: &MobilePushSubscription,
    notification: &MobilePushNotification,
    now_secs: u64,
) -> Result<(), PushSendError> {
    let plaintext = serde_json::to_vec(notification)
        .map_err(|error| PushSendError::Encryption(format!("serialize notification: {error}")))?;

    let ua_public = decode_key(&subscription.p256dh.0, "p256dh")?;
    let auth_secret = decode_key(&subscription.auth.0, "auth")?;
    if auth_secret.len() != 16 {
        return Err(PushSendError::InvalidSubscription(format!(
            "auth secret must be 16 bytes, got {}",
            auth_secret.len()
        )));
    }

    let body = encrypt(&ua_public, &auth_secret, &plaintext)?;
    let authorization = vapid_authorization(subscription, &subscription.endpoint.0, now_secs)?;

    let response = client
        .post(&subscription.endpoint.0)
        .header("Authorization", authorization)
        .header("Content-Encoding", "aes128gcm")
        .header("Content-Type", "application/octet-stream")
        .header("TTL", PUSH_TTL_SECONDS.to_string())
        .header("Urgency", "high")
        .body(body)
        .send()
        .await
        .map_err(|error| PushSendError::Transport(error.to_string()))?;

    let status = response.status();
    if status.is_success() {
        return Ok(());
    }
    if status == reqwest::StatusCode::NOT_FOUND || status == reqwest::StatusCode::GONE {
        return Err(PushSendError::SubscriptionGone);
    }
    let body = response.text().await.unwrap_or_default();
    Err(PushSendError::Rejected {
        status: status.as_u16(),
        body,
    })
}

/// RFC 8291 §3.4 key derivation plus RFC 8188 record framing.
fn encrypt(
    ua_public: &[u8],
    auth_secret: &[u8],
    plaintext: &[u8],
) -> Result<Vec<u8>, PushSendError> {
    let ua_key = PublicKey::from_sec1_bytes(ua_public)
        .map_err(|error| PushSendError::InvalidSubscription(format!("p256dh: {error}")))?;

    let as_secret = SecretKey::random(&mut OsRng);
    let as_public_point = as_secret.public_key().to_encoded_point(false);
    let as_public = as_public_point.as_bytes();

    let shared = diffie_hellman(as_secret.to_nonzero_scalar(), ua_key.as_affine());

    // The IKM binds both public keys, so a message encrypted for one device
    // cannot be replayed at another.
    let mut key_info = Vec::with_capacity(14 + ua_public.len() + as_public.len());
    key_info.extend_from_slice(b"WebPush: info\0");
    key_info.extend_from_slice(ua_public);
    key_info.extend_from_slice(as_public);

    let mut ikm = [0u8; 32];
    Hkdf::<Sha256>::new(Some(auth_secret), shared.raw_secret_bytes())
        .expand(&key_info, &mut ikm)
        .map_err(|error| PushSendError::Encryption(format!("expand ikm: {error}")))?;

    let mut salt = [0u8; 16];
    fill_random(&mut salt);

    let hkdf = Hkdf::<Sha256>::new(Some(&salt), &ikm);
    let mut cek = [0u8; 16];
    hkdf.expand(b"Content-Encoding: aes128gcm\0", &mut cek)
        .map_err(|error| PushSendError::Encryption(format!("expand cek: {error}")))?;
    let mut nonce = [0u8; 12];
    hkdf.expand(b"Content-Encoding: nonce\0", &mut nonce)
        .map_err(|error| PushSendError::Encryption(format!("expand nonce: {error}")))?;

    // A single record, so the padding delimiter is 0x02 ("last record").
    let mut record = Vec::with_capacity(plaintext.len() + 1);
    record.extend_from_slice(plaintext);
    record.push(0x02);

    let cipher = Aes128Gcm::new(Key::<Aes128Gcm>::from_slice(&cek));
    let ciphertext = cipher
        .encrypt(
            Nonce::from_slice(&nonce),
            Payload {
                msg: &record,
                aad: b"",
            },
        )
        .map_err(|error| PushSendError::Encryption(format!("aes128gcm: {error}")))?;

    let mut body = Vec::with_capacity(21 + as_public.len() + ciphertext.len());
    body.extend_from_slice(&salt);
    body.extend_from_slice(&RECORD_SIZE.to_be_bytes());
    body.push(
        u8::try_from(as_public.len())
            .map_err(|_| PushSendError::Encryption("ephemeral key too long".to_owned()))?,
    );
    body.extend_from_slice(as_public);
    body.extend_from_slice(&ciphertext);
    Ok(body)
}

/// RFC 8292 `vapid` authorization: an ES256 JWT plus the public key that
/// `pushManager.subscribe` was called with.
fn vapid_authorization(
    subscription: &MobilePushSubscription,
    endpoint: &str,
    now_secs: u64,
) -> Result<String, PushSendError> {
    let audience = endpoint_audience(endpoint)?;

    let private = decode_key(&subscription.vapid_private_key.0, "vapid private key")?;
    let signing_key = SigningKey::from_slice(&private).map_err(|error| {
        PushSendError::InvalidSubscription(format!("vapid private key: {error}"))
    })?;

    let header = URL_SAFE_NO_PAD.encode(br#"{"typ":"JWT","alg":"ES256"}"#);
    let claims = serde_json::json!({
        "aud": audience,
        "exp": now_secs + VAPID_TOKEN_LIFETIME_SECONDS,
        "sub": VAPID_SUBJECT,
    });
    let claims =
        URL_SAFE_NO_PAD
            .encode(serde_json::to_vec(&claims).map_err(|error| {
                PushSendError::Encryption(format!("serialize claims: {error}"))
            })?);

    let signing_input = format!("{header}.{claims}");
    let signature: Signature = signing_key.sign(signing_input.as_bytes());
    let token = format!(
        "{signing_input}.{}",
        URL_SAFE_NO_PAD.encode(signature.to_bytes())
    );

    Ok(format!(
        "vapid t={token}, k={}",
        subscription.vapid_public_key.0
    ))
}

/// The JWT audience is the endpoint's origin, scheme and authority only.
fn endpoint_audience(endpoint: &str) -> Result<String, PushSendError> {
    let url = url::Url::parse(endpoint)
        .map_err(|error| PushSendError::InvalidSubscription(format!("endpoint: {error}")))?;
    let host = url
        .host_str()
        .ok_or_else(|| PushSendError::InvalidSubscription("endpoint has no host".to_owned()))?;
    match url.port() {
        Some(port) => Ok(format!("{}://{host}:{port}", url.scheme())),
        None => Ok(format!("{}://{host}", url.scheme())),
    }
}

fn decode_key(value: &str, field: &str) -> Result<Vec<u8>, PushSendError> {
    URL_SAFE_NO_PAD
        .decode(value)
        .map_err(|error| PushSendError::InvalidSubscription(format!("{field}: {error}")))
}

fn fill_random(buffer: &mut [u8]) {
    use p256::elliptic_curve::rand_core::RngCore;
    OsRng.fill_bytes(buffer);
}
