//! Claude native skill discovery: one session-owned inline plugin.
//!
//! Claude Code discovers skills from a plugin directory passed with
//! `--plugin-dir`. Tyde materializes a session-scoped plugin root containing a
//! **wrapper directory per selected skill**:
//!
//! ```text
//! <private 0700 temp root>/
//! ├── .claude-plugin/plugin.json          generated, 0600, no `skills` key
//! └── skills/<name>/
//!     ├── SKILL.md                        generated, 0600 — see below
//!     └── <resource> -> <store>/<name>/<resource>   (symlink, non-SKILL.md only)
//! ```
//!
//! `SKILL.md` is **not** symlinked. Tyde reads the store's `SKILL.md` exactly
//! once, validates those bytes, and writes a semantic snapshot built from the
//! same bytes. What Claude loads is therefore what Tyde inspected: there is no
//! window in which the file can change between validation and load. The
//! snapshot carries the complete parsed frontmatter mapping with only `name`
//! replaced by the synthesized wrapper name, plus the instructional body
//! verbatim.
//!
//! Frontmatter is the selected skill's semantic payload. Selecting a skill
//! explicitly, or installing it for the Default agent, authorizes passing its
//! complete valid mapping to Claude, including permission, activation, and
//! unknown fields. Tyde does not reinterpret or filter those declarations. This
//! is separate from the generated plugin container: Tyde still controls its
//! manifest and refuses resource paths that could alter that filesystem shape.
//!
//! Other top-level entries are symlinked so a skill's relative assets and
//! scripts still resolve — that is what keeps this O(number of skills) instead
//! of copying a 342 MB / 14k-file store per session. Those resources are not
//! parsed or executed by the loader, and each must resolve inside its own skill
//! directory before it is linked; the link then points at that **canonical**
//! target, not at the entry path, so it cannot be re-pointed afterwards.
//!
//! **LIVE VERIFICATION REQUIRED.** The 2.1.220 smoke proved relative resources
//! resolve through a *directory* symlink of a whole skill. It did **not** cover
//! this wrapper shape, where `SKILL.md` is a real file beside per-resource
//! links. Whether Claude resolves a skill's relative links against the wrapper
//! directory (correct) or against the resolved location of some other entry is
//! unproven. A paid Haiku smoke of exactly this layout is required before the
//! wrapper strategy can be called verified; the offline tests below pin Tyde's
//! side of it only.
//!
//! Verified against Claude Code 2.1.220 in the exact
//! `--print --output-format stream-json` mode Tyde spawns (evidence:
//! `claude-live-smoke.md`): skills reach the model as `tyde-skills:<name>`,
//! appear in the `system/init` frame the CLI emits before any provider request,
//! load their bodies lazily at invocation, and resolve relative links through a
//! directory symlink. `plugin.json` must not declare `skills` — declaring it
//! shadows the auto-loaded folder and turns manifest-relative paths into a
//! traversal check.
//!
//! **Tyde never writes the user's Claude configuration or skill store.** It
//! writes only inside its own private per-session temp root, and reads the store
//! read-only. Loading any plugin makes the *Claude CLI* record bounded usage
//! telemetry in `~/.claude.json` (`pluginUsage`, `skillUsage`); that is expected
//! CLI behaviour on any `--plugin-dir` run, is bounded (the plugin name is
//! fixed, and `skillUsage` gains at most one key per distinct skill invoked),
//! and is not something Tyde performs or can suppress.

use std::collections::{BTreeMap, BTreeSet};
use std::path::Path;

use crate::agent::customization::{ResolvedSkill, SkillSelection};
use crate::backend::skill_projection::{
    DescriptionPolicy, InspectedSkill, ProjectionPolicy, SkillRefusal, create_private_dir,
    create_private_root, discard_wrapper, inspect_skill, write_private_file, write_wrapper,
};

/// Fixed plugin name. Skills are addressed as `tyde-skills:<name>`.
pub(crate) const TYDE_SKILLS_PLUGIN_NAME: &str = "tyde-skills";

/// The only flag used to load the session plugin.
///
/// `--plugin-dir` is documented in `--help`, so its absence is a real capability
/// signal. The undocumented `--plugin-dir-no-mcp` variant is deliberately not
/// used: it can only be detected by attempting it and reacting to a startup
/// failure, and the retry that requires is a race for no benefit here. This
/// root is generated by Tyde and contains no `.mcp.json`, so there is no MCP
/// config for the CLI to read either way.
pub(crate) const CLAUDE_PLUGIN_DIR_FLAG: &str = "--plugin-dir";

/// How a selected skill is projected for Claude.
///
/// The refused names' frontmatter equivalents are deliberately preserved as
/// selected-skill semantics. Files such as `.mcp.json` and `hooks.json` are
/// different: linking them would modify the plugin container outside the
/// inspected `SKILL.md` snapshot or collide with Tyde-owned configuration.
///
/// A missing description stays missing: 2.1.220 loads a `SKILL.md` with no
/// frontmatter at all, so there is nothing to rescue by inventing one.
const CLAUDE_PROJECTION: ProjectionPolicy = ProjectionPolicy {
    refused_resource_names: &[".claude-plugin", ".mcp.json", "hooks.json", ".claude"],
    description: DescriptionPolicy::Optional,
};

/// One skill that was successfully materialized.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct PreparedSkill {
    /// Synthesized wrapper name: the directory name, the frontmatter `name`, and
    /// the id the model addresses. Safe by construction and unique within the
    /// session.
    pub(crate) name: String,
    /// `tyde-skills:<name>` — what the CLI must report in its `init` frame.
    pub(crate) namespaced: String,
    /// The store directory name the user knows this skill by. Shown alongside
    /// the exposed name when the two differ, so a renamed skill is never a
    /// mystery.
    pub(crate) source_name: String,
    /// One-line description used in the overlay. The wrapper independently
    /// preserves the source value or receives the real store fallback.
    pub(crate) description: Option<String>,
}

impl PreparedSkill {
    /// Add Claude's namespacing to a projected skill. The namespaced id is
    /// derived from the same wrapper name that became the directory and the
    /// frontmatter `name`, so all three agree by construction.
    fn from_projected(projected: crate::backend::skill_projection::ProjectedSkill) -> Self {
        Self {
            namespaced: namespaced_skill_name(&projected.name),
            name: projected.name,
            source_name: projected.source_name,
            description: projected.description,
        }
    }
}

/// Outcome of materializing a selection.
#[derive(Debug)]
pub(crate) struct PreparedPlugin {
    /// `None` when no skill survived; the refusals still travel.
    pub(crate) plugin: Option<ClaudeSkillPlugin>,
    pub(crate) prepared: Vec<PreparedSkill>,
    pub(crate) refusals: Vec<SkillRefusal>,
}

/// A materialized session plugin root, owning a private temp directory.
///
/// The directory is allocated **before any write**, so every partial failure
/// rolls back by dropping this value: there is no path that leaves half a
/// plugin behind for the CLI to load.
#[derive(Debug)]
pub(crate) struct ClaudeSkillPlugin {
    guard: tempfile::TempDir,
    exposed: Vec<String>,
}

impl ClaudeSkillPlugin {
    pub(crate) fn root(&self) -> &Path {
        self.guard.path()
    }

    /// `tyde-skills:<name>` for every materialized skill, sorted.
    pub(crate) fn exposed(&self) -> &[String] {
        &self.exposed
    }

    /// Materialize `skills` into a fresh private root under `parent`
    /// (`std::env::temp_dir()` when `None`).
    pub(crate) fn prepare(
        parent: Option<&Path>,
        skills: &[ResolvedSkill],
    ) -> Result<PreparedPlugin, String> {
        let mut refusals = Vec::new();
        let mut inspected: Vec<InspectedSkill> = Vec::new();
        let mut claimed: BTreeSet<String> = BTreeSet::new();

        // Inspect everything first, so a per-skill problem is a refusal the
        // caller can weigh against its selection policy rather than a
        // half-built root.
        for skill in skills {
            match inspect_skill(skill, &mut claimed, CLAUDE_PROJECTION) {
                Ok(entry) => inspected.push(entry),
                Err(reason) => refusals.push(SkillRefusal {
                    name: skill.name.clone(),
                    reason,
                }),
            }
        }

        if inspected.is_empty() {
            return Ok(PreparedPlugin {
                plugin: None,
                prepared: Vec::new(),
                refusals,
            });
        }

        // Creating the root, the manifest, or the skills directory is a
        // *global* failure: without them there is no plugin at all, and no
        // per-skill degradation can rescue that. The guard exists before the
        // first write, so any `?` here removes everything written so far.
        let guard = create_private_root(parent, "tyde-claude-skills-")?;
        let manifest_dir = guard.path().join(".claude-plugin");
        create_private_dir(&manifest_dir)?;
        write_private_file(&manifest_dir.join("plugin.json"), &plugin_manifest_json())?;
        let skills_dir = guard.path().join("skills");
        create_private_dir(&skills_dir)?;

        let mut prepared = Vec::new();
        let mut exposed = Vec::new();
        for entry in inspected {
            // A *per-skill* write failure omits that skill and keeps the rest,
            // matching how an inspection failure behaves. The caller's selection
            // policy — fail-closed for explicit, best-effort for Default — then
            // applies uniformly to every reason a skill did not make it.
            match write_wrapper(&skills_dir, &entry) {
                Ok(()) => {
                    let skill = PreparedSkill::from_projected(entry.projected);
                    exposed.push(skill.namespaced.clone());
                    prepared.push(skill);
                }
                Err(reason) => {
                    // Remove the partial wrapper so the CLI never sees half a
                    // skill; the root itself stays valid for the others.
                    discard_wrapper(&skills_dir, &entry.projected.name);
                    refusals.push(SkillRefusal {
                        name: entry.source_name,
                        reason,
                    });
                }
            }
        }
        exposed.sort();

        if prepared.is_empty() {
            // Every skill failed during the write phase. Drop the root rather
            // than pointing the CLI at an empty plugin.
            drop(guard);
            return Ok(PreparedPlugin {
                plugin: None,
                prepared: Vec::new(),
                refusals,
            });
        }

        Ok(PreparedPlugin {
            plugin: Some(Self { guard, exposed }),
            prepared,
            refusals,
        })
    }

    /// Remove the session root.
    ///
    /// The root is **entirely Tyde-owned**: Tyde created it, wrote every regular
    /// file in it, and created every link in it. So it is removed recursively,
    /// which is the honest contract — there is nothing in there that belongs to
    /// anyone else, and pretending otherwise led to a "left in place" branch
    /// that promised more than it could deliver.
    ///
    /// `std::fs::remove_dir_all` unlinks symlinks rather than following them, so
    /// removing a root full of links into the user's skill store cannot touch
    /// anything in that store.
    ///
    /// Idempotent, so the `TempDir` drop that follows an explicit shutdown is a
    /// no-op.
    pub(crate) fn cleanup(&self) -> Result<(), String> {
        let root = self.guard.path();
        if !root.exists() {
            return Ok(());
        }
        std::fs::remove_dir_all(root)
            .map_err(|err| format!("Failed to remove {}: {err}", root.display()))
    }
}

/// Minimal manifest. `skills` is deliberately absent: declaring it shadows the
/// auto-loaded `skills/` folder and turns manifest-relative paths into a
/// traversal check, which breaks resource resolution.
fn plugin_manifest_json() -> String {
    format!(
        "{{\n  \"name\": \"{TYDE_SKILLS_PLUGIN_NAME}\",\n  \
         \"description\": \"Skills installed in Tyde\",\n  \
         \"version\": \"0.0.0\"\n}}\n"
    )
}

pub(crate) fn namespaced_skill_name(name: &str) -> String {
    format!("{TYDE_SKILLS_PLUGIN_NAME}:{name}")
}

/// Does this CLI's `--help` advertise plugin sideloading?
pub(crate) fn help_text_supports_plugin_dir(help: &str) -> bool {
    help.contains(CLAUDE_PLUGIN_DIR_FLAG)
}

/// Notice for a CLI that cannot sideload a plugin. Names the flag rather than a
/// version: one installed CLI cannot establish a floor version, and a wrong
/// version number in a message is worse than none.
pub(crate) fn unsupported_plugin_dir_notice() -> String {
    format!(
        "Tyde started this Claude session without its installed skills: this Claude CLI does not \
         support `{CLAUDE_PLUGIN_DIR_FLAG}`, which is how Tyde exposes them. Skills are \
         discovered natively from a session-scoped `{TYDE_SKILLS_PLUGIN_NAME}` plugin; Tyde will \
         not fall back to pasting skill bodies into the prompt. Upgrade the Claude CLI to get \
         them back. The session works normally otherwise."
    )
}

/// Verify `claude plugin list --json` output against the root Tyde built.
///
/// This is the **stable machine-readable** surface, and it is the only one:
/// `plugin list --json` is a documented flag emitting a JSON array with `id`,
/// `enabled`, and `installPath`. It proves the CLI accepted `--plugin-dir`, read
/// the manifest, and enabled the plugin — every *global* failure mode — at zero
/// provider cost, before the session process starts.
///
/// It deliberately does **not** enumerate skills. `plugin details` does, but only
/// as human-readable text (`Skills (2)  a, b`) with no documented format and no
/// `--json`, and `plugin validate --strict` prints "Validation failed" while
/// exiting 0. Parsing either would be building a gate on an unstable surface, so
/// per-skill verification is left to the `init`-frame consistency check.
pub(crate) fn verify_plugin_inventory(output: &str, expected_root: &Path) -> Result<(), String> {
    let parsed: serde_json::Value = serde_json::from_str(output).map_err(|err| {
        format!(
            "Claude's plugin inventory was not valid JSON, so Tyde cannot confirm the session \
             plugin loaded: {err}"
        )
    })?;
    let entries = parsed.as_array().ok_or_else(|| {
        "Claude's plugin inventory was not a JSON array, so Tyde cannot confirm the session \
         plugin loaded"
            .to_string()
    })?;
    let expected_id = format!("{TYDE_SKILLS_PLUGIN_NAME}@inline");
    let matching: Vec<&serde_json::Value> = entries
        .iter()
        .filter(|entry| entry.get("id").and_then(|id| id.as_str()) == Some(expected_id.as_str()))
        .collect();
    // More than one entry under our id means the CLI resolved the name from two
    // places. Which one carries this session's skills is then a guess, and a
    // guess is exactly what this check exists to remove.
    if matching.len() > 1 {
        return Err(format!(
            "Claude reported {} plugins under the id '{expected_id}', so Tyde cannot tell \
             which one this session's skills came from",
            matching.len()
        ));
    }
    let entry = matching.first().ok_or_else(|| {
        format!(
            "Claude did not load the '{expected_id}' plugin from {}, so this session's skills \
             would be missing",
            expected_root.display()
        )
    })?;
    if entry.get("enabled").and_then(serde_json::Value::as_bool) != Some(true) {
        return Err(format!(
            "Claude loaded '{expected_id}' but reported it as disabled, so this session's \
             skills would be unavailable"
        ));
    }
    // A non-empty `errors` array means the CLI took the plugin but had
    // complaints about it. Whatever it could not process is precisely what
    // would go missing later, so this is a startup failure rather than a note.
    if let Some(errors) = entry.get("errors").and_then(serde_json::Value::as_array)
        && !errors.is_empty()
    {
        let rendered = errors
            .iter()
            .map(|error| {
                error
                    .as_str()
                    .map(str::to_string)
                    .unwrap_or_else(|| error.to_string())
            })
            .collect::<Vec<_>>()
            .join("; ");
        return Err(format!(
            "Claude reported {} problem(s) loading '{expected_id}': {rendered}",
            errors.len()
        ));
    }
    let reported = entry
        .get("installPath")
        .and_then(|path| path.as_str())
        .ok_or_else(|| {
            format!(
                "Claude reported '{expected_id}' without an install path, so Tyde cannot \
                 confirm it loaded this session's root"
            )
        })?;
    // Exact canonical equality. Tyde's own root must resolve — it was just
    // created, so a failure there is a real error. The *reported* root is a
    // value the CLI handed us: a path that does not exist cannot be the root
    // Tyde built, so that is a rejection of the entry, not an OS error to
    // propagate. Reporting `ENOENT` for a foreign root described the syscall
    // rather than the finding.
    let expected_canonical = std::fs::canonicalize(expected_root).map_err(|err| {
        format!(
            "Tyde could not resolve this session's plugin root {}: {err}",
            expected_root.display()
        )
    })?;
    match std::fs::canonicalize(reported) {
        Ok(reported_canonical) if reported_canonical == expected_canonical => Ok(()),
        Ok(reported_canonical) => Err(format!(
            "Claude loaded '{expected_id}' from {}, not from this session's root {}",
            reported_canonical.display(),
            expected_canonical.display()
        )),
        Err(_) => Err(format!(
            "Claude loaded '{expected_id}' from {reported}, which Tyde could not resolve, so \
             it is not from this session's root {}",
            expected_canonical.display()
        )),
    }
}

/// Result of checking a CLI `init` frame against what Tyde materialized.
///
/// There is deliberately no fatal variant. A session whose skills did not all
/// arrive is a *worse* session, not an unusable one, and killing it takes away
/// every other skill and the whole conversation to punish one name. So the gap
/// is reported and the session runs.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) enum InitFrameVerdict {
    Verified,
    /// At least one materialized skill is not reachable under the id Tyde told
    /// the model to use. Carries the user-visible notice naming each one, what
    /// happened to it, and — when Claude kept its own copy — the id that does
    /// work.
    Degraded(String),
}

/// The id an expected skill is actually reachable under, if any.
///
/// Claude drops a plugin skill whose bare name collides with one the user
/// already has, keeping its own copy and logging the skip only at debug level.
/// The capability is therefore still present, just under a different id — which
/// is the difference between "degraded" and "gone", and the reason this looks
/// past the namespace before calling anything missing.
fn user_owned_alternative<'a>(expected_id: &str, reported: &[&'a str]) -> Option<&'a str> {
    let bare = expected_id
        .rsplit_once(':')
        .map_or(expected_id, |(_, name)| name);
    reported
        .iter()
        .copied()
        .filter(|candidate| *candidate != expected_id)
        .find(|candidate| {
            let candidate_bare = candidate
                .rsplit_once(':')
                .map_or(*candidate, |(_, name)| name);
            candidate_bare == bare
        })
}

/// Check that every materialized skill was loaded, exactly once.
///
/// `reported` is the `init` frame's `skills` array; `None` means the frame did
/// not carry the field. Anything short of a clean match produces a notice rather
/// than a refusal: the session still has whatever else it materialized, and the
/// user is told exactly what it does not have.
pub(crate) fn verify_init_frame(
    expected: &[String],
    reported: Option<&[String]>,
) -> InitFrameVerdict {
    if expected.is_empty() {
        return InitFrameVerdict::Verified;
    }
    let Some(reported) = reported else {
        return InitFrameVerdict::Degraded(
            "Claude's init frame did not report a 'skills' field, so Tyde cannot confirm this \
             session's skills were loaded. The session continues; if a skill turns out to be \
             missing, ask for it by name and Claude will report that it is unavailable."
                .to_string(),
        );
    };

    let mut counts: BTreeMap<&str, usize> = BTreeMap::new();
    for name in reported {
        *counts.entry(name.as_str()).or_default() += 1;
    }
    let reported_names: Vec<&str> = reported.iter().map(String::as_str).collect();

    let mut notices: Vec<String> = Vec::new();

    let duplicated: Vec<&str> = expected
        .iter()
        .map(String::as_str)
        .filter(|name| counts.get(name).copied().unwrap_or(0) > 1)
        .collect();
    if !duplicated.is_empty() {
        notices.push(format!(
            "Claude reported {} more than once, so the '{TYDE_SKILLS_PLUGIN_NAME}' namespace \
             collides with another loaded skill and Tyde cannot tell which body will run.",
            duplicated.join(", ")
        ));
    }

    let mut superseded: Vec<String> = Vec::new();
    let mut missing: Vec<&str> = Vec::new();
    for name in expected.iter().map(String::as_str) {
        if counts.contains_key(name) {
            continue;
        }
        match user_owned_alternative(name, &reported_names) {
            Some(alternative) => superseded.push(format!("{name} (loaded as '{alternative}')")),
            None => missing.push(name),
        }
    }

    if !superseded.is_empty() {
        notices.push(format!(
            "Claude already had a skill of the same name for {}, and resolves that collision in \
             favour of its own copy. The skill is still available — invoke it under the name in \
             brackets rather than the '{TYDE_SKILLS_PLUGIN_NAME}:' one. Rename the Tyde skill if \
             you want this session to use Tyde's copy instead.",
            superseded.join(", ")
        ));
    }
    if !missing.is_empty() {
        notices.push(format!(
            "Claude did not load {}, so this session does not have {}. Everything else the \
             session selected is available normally.",
            missing.join(", "),
            if missing.len() == 1 { "it" } else { "them" }
        ));
    }

    if notices.is_empty() {
        InitFrameVerdict::Verified
    } else {
        InitFrameVerdict::Degraded(notices.join(" "))
    }
}

/// The steering overlay describing how to reach Tyde skills.
///
/// Built **only from skills that were actually materialized**, so the model is
/// never told about a skill the session failed to expose. `AllInstalled` gets one
/// constant-size paragraph and no enumeration: Claude's own listing already
/// carries every name and description, and re-listing them would rebuild the
/// duplication this work removes. `Explicit` enumerates, because a custom
/// agent's selection is a deliberate statement of intent. Neither carries a body.
pub(crate) fn native_skill_overlay(
    selection: SkillSelection,
    prepared: &[PreparedSkill],
) -> String {
    match selection {
        SkillSelection::AllInstalled => format!(
            "Skills installed in Tyde are available through the \
             `{TYDE_SKILLS_PLUGIN_NAME}` plugin and are addressed as \
             `{TYDE_SKILLS_PLUGIN_NAME}:<name>`. Their names and descriptions \
             are already listed among your available skills; read a skill only \
             when you invoke it. If one of those ids does not resolve, a skill \
             of the same name was already installed here and won the name — try \
             the bare `<name>` before reporting the skill as unavailable."
        ),
        SkillSelection::Explicit => {
            let mut lines = vec![format!(
                "This agent selected these Tyde skills, available through the \
                 `{TYDE_SKILLS_PLUGIN_NAME}` plugin as `{TYDE_SKILLS_PLUGIN_NAME}:<name>`:"
            )];
            for skill in prepared {
                // Show the store name too when synthesis renamed the skill, so
                // the id the model uses is never a mystery.
                let label = if skill.name == skill.source_name {
                    skill.name.clone()
                } else {
                    format!("{} (installed as '{}')", skill.name, skill.source_name)
                };
                match skill.description.as_deref() {
                    Some(description) if !description.is_empty() => {
                        lines.push(format!("- {label} — {description}"));
                    }
                    _ => lines.push(format!("- {label}")),
                }
            }
            lines.push(
                "If one of those ids does not resolve, a skill of the same name was already \
                 installed here and won the name — try the bare `<name>` before reporting the \
                 skill as unavailable."
                    .to_string(),
            );
            lines.join("\n")
        }
    }
}

/// User-visible notice for a session that started without some of its skills.
///
/// Used for every selection, including a custom agent's explicit one: a skill
/// Tyde could not materialize costs that session a capability, and refusing to
/// start costs it the capability *and* every other one it asked for.
pub(crate) fn degraded_default_notice(refusals: &[SkillRefusal]) -> String {
    let mut lines = vec![format!(
        "Tyde started this Claude session without {} of its selected skill(s):",
        refusals.len()
    )];
    for refusal in refusals {
        lines.push(format!("- {}", refusal.describe()));
    }
    lines.push(
        "The rest of the session's skills are available normally. Fix or remove the skills above \
         to expose them."
            .to_string(),
    );
    lines.join("\n")
}
