//! Claude native skill discovery: one session-owned inline plugin.
//!
//! Claude Code discovers skills from a plugin directory passed with
//! `--plugin-dir`. Tyde materializes a session-scoped plugin root containing a
//! **wrapper directory per selected skill**:
//!
//! ```text
//! <private 0700 temp root>/
//! ├── .claude-plugin/plugin.json          generated, 0600, no `skills` key
//! └── skills/<name>/
//!     ├── SKILL.md                        generated, 0600 — see below
//!     └── <resource> -> <store>/<name>/<resource>   (symlink, non-SKILL.md only)
//! ```
//!
//! `SKILL.md` is **not** symlinked. Tyde reads the store's `SKILL.md` exactly
//! once, validates those bytes, and writes a sanitized snapshot built from the
//! same bytes. What Claude loads is therefore what Tyde inspected: there is no
//! window in which the file can change between validation and load, and a skill
//! cannot smuggle an activation key past the check by being rewritten
//! afterwards. The snapshot carries a synthesized `name`/`description`
//! frontmatter and the instructional body verbatim; every other frontmatter key
//! is dropped by construction.
//!
//! Other top-level entries are symlinked so a skill's relative assets and
//! scripts still resolve — that is what keeps this O(number of skills) instead
//! of copying a 342 MB / 14k-file store per session. Those resources are not
//! parsed or executed by the loader, and each must resolve inside its own skill
//! directory before it is linked; the link then points at that **canonical**
//! target, not at the entry path, so it cannot be re-pointed afterwards.
//!
//! **LIVE VERIFICATION REQUIRED.** The 2.1.220 smoke proved relative resources
//! resolve through a *directory* symlink of a whole skill. It did **not** cover
//! this wrapper shape, where `SKILL.md` is a real file beside per-resource
//! links. Whether Claude resolves a skill's relative links against the wrapper
//! directory (correct) or against the resolved location of some other entry is
//! unproven. A paid Haiku smoke of exactly this layout is required before the
//! wrapper strategy can be called verified; the offline tests below pin Tyde's
//! side of it only.
//!
//! Verified against Claude Code 2.1.220 in the exact
//! `--print --output-format stream-json` mode Tyde spawns (evidence:
//! `claude-live-smoke.md`): skills reach the model as `tyde-skills:<name>`,
//! appear in the `system/init` frame the CLI emits before any provider request,
//! load their bodies lazily at invocation, and resolve relative links through a
//! directory symlink. `plugin.json` must not declare `skills` — declaring it
//! shadows the auto-loaded folder and turns manifest-relative paths into a
//! traversal check.
//!
//! **Tyde never writes the user's Claude configuration or skill store.** It
//! writes only inside its own private per-session temp root, and reads the store
//! read-only. Loading any plugin makes the *Claude CLI* record bounded usage
//! telemetry in `~/.claude.json` (`pluginUsage`, `skillUsage`); that is expected
//! CLI behaviour on any `--plugin-dir` run, is bounded (the plugin name is
//! fixed, and `skillUsage` gains at most one key per distinct skill invoked),
//! and is not something Tyde performs or can suppress.

use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};

use crate::agent::customization::{ResolvedSkill, SkillSelection};

/// Fixed plugin name. Skills are addressed as `tyde-skills:<name>`.
pub(crate) const TYDE_SKILLS_PLUGIN_NAME: &str = "tyde-skills";

/// The only flag used to load the session plugin.
///
/// `--plugin-dir` is documented in `--help`, so its absence is a real capability
/// signal. The undocumented `--plugin-dir-no-mcp` variant is deliberately not
/// used: it can only be detected by attempting it and reacting to a startup
/// failure, and the retry that requires is a race for no benefit here. This
/// root is generated by Tyde and contains no `.mcp.json`, so there is no MCP
/// config for the CLI to read either way.
pub(crate) const CLAUDE_PLUGIN_DIR_FLAG: &str = "--plugin-dir";

/// Longest exposed skill name Tyde will produce, suffix included.
///
/// Skill names become directory names, frontmatter values, and namespaced ids.
/// 64 is comfortably under every path-component limit Tyde needs to survive and
/// short enough to stay readable in the model's skill listing.
const EXPOSED_NAME_MAX_LEN: usize = 64;

/// The **only** frontmatter keys a Tyde wrapper will carry over.
///
/// This is an allowlist, not a denylist, and that is the whole point: a denylist
/// silently changes a skill's semantics whenever Claude grows a field nobody
/// added to the list. `name` and `description` are the two fields Claude
/// documents for a skill and the two that are inert — they say what the skill is
/// called and what it is for, and nothing else. Everything else, whether it is a
/// known behaviour-changing field (`allowed-tools`, `model`,
/// `disable-model-invocation`), a known activation field (`hooks`,
/// `mcpServers`, `lsp`), or a field this version of Tyde has never heard of, is
/// a **refusal**. Refusing is visible; quietly dropping a field that changed the
/// skill's behaviour is not.
const ALLOWED_FRONTMATTER_KEYS: &[&str] = &["name", "description"];

/// Known activation keys, named separately only so the refusal message can say
/// *why* rather than "unrecognized". Not a gate — the allowlist is the gate.
const KNOWN_ACTIVATION_KEYS: &[&str] = &[
    "hooks",
    "mcp",
    "mcpservers",
    "mcp_servers",
    "lsp",
    "lspservers",
    "lsp_servers",
    "monitors",
    "agents",
    "commands",
    "workflows",
    "outputstyles",
    "output_styles",
    "statusline",
    "permissions",
    "allowed-tools",
    "allowed_tools",
    "disable-model-invocation",
    "disable_model_invocation",
    "model",
];

/// Top-level resource names never linked into a wrapper, because they name
/// plugin-level activation surfaces. A skill directory has no business shipping
/// one, and a wrapper must not become a place where one could be found.
const REFUSED_RESOURCE_NAMES: &[&str] = &[".claude-plugin", ".mcp.json", "hooks.json", ".claude"];

/// Why one selected skill was not exposed.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct SkillRefusal {
    pub(crate) name: String,
    pub(crate) reason: String,
}

impl SkillRefusal {
    pub(crate) fn describe(&self) -> String {
        format!("skill '{}' was not exposed: {}", self.name, self.reason)
    }
}

/// One skill that was successfully materialized.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct PreparedSkill {
    /// Synthesized wrapper name: the directory name, the frontmatter `name`, and
    /// the id the model addresses. Safe by construction and unique within the
    /// session.
    pub(crate) name: String,
    /// `tyde-skills:<name>` — what the CLI must report in its `init` frame.
    pub(crate) namespaced: String,
    /// The store directory name the user knows this skill by. Shown alongside
    /// the exposed name when the two differ, so a renamed skill is never a
    /// mystery.
    pub(crate) source_name: String,
    /// Description used in the overlay and in the generated frontmatter.
    pub(crate) description: Option<String>,
}

/// Outcome of materializing a selection.
#[derive(Debug)]
pub(crate) struct PreparedPlugin {
    /// `None` when no skill survived; the refusals still travel.
    pub(crate) plugin: Option<ClaudeSkillPlugin>,
    pub(crate) prepared: Vec<PreparedSkill>,
    pub(crate) refusals: Vec<SkillRefusal>,
}

/// A materialized session plugin root, owning a private temp directory.
///
/// The directory is allocated **before any write**, so every partial failure
/// rolls back by dropping this value: there is no path that leaves half a
/// plugin behind for the CLI to load.
#[derive(Debug)]
pub(crate) struct ClaudeSkillPlugin {
    guard: tempfile::TempDir,
    exposed: Vec<String>,
}

impl ClaudeSkillPlugin {
    pub(crate) fn root(&self) -> &Path {
        self.guard.path()
    }

    /// `tyde-skills:<name>` for every materialized skill, sorted.
    pub(crate) fn exposed(&self) -> &[String] {
        &self.exposed
    }

    /// Materialize `skills` into a fresh private root under `parent`
    /// (`std::env::temp_dir()` when `None`).
    pub(crate) fn prepare(
        parent: Option<&Path>,
        skills: &[ResolvedSkill],
    ) -> Result<PreparedPlugin, String> {
        let mut refusals = Vec::new();
        let mut inspected: Vec<InspectedSkill> = Vec::new();
        let mut claimed: BTreeSet<String> = BTreeSet::new();

        // Inspect everything first, so a per-skill problem is a refusal the
        // caller can weigh against its selection policy rather than a
        // half-built root.
        for skill in skills {
            match inspect_skill(skill, &mut claimed) {
                Ok(entry) => inspected.push(entry),
                Err(reason) => refusals.push(SkillRefusal {
                    name: skill.name.clone(),
                    reason,
                }),
            }
        }

        if inspected.is_empty() {
            return Ok(PreparedPlugin {
                plugin: None,
                prepared: Vec::new(),
                refusals,
            });
        }

        // Creating the root, the manifest, or the skills directory is a
        // *global* failure: without them there is no plugin at all, and no
        // per-skill degradation can rescue that. The guard exists before the
        // first write, so any `?` here removes everything written so far.
        let guard = create_private_root(parent)?;
        let manifest_dir = guard.path().join(".claude-plugin");
        create_private_dir(&manifest_dir)?;
        write_private_file(&manifest_dir.join("plugin.json"), &plugin_manifest_json())?;
        let skills_dir = guard.path().join("skills");
        create_private_dir(&skills_dir)?;

        let mut prepared = Vec::new();
        let mut exposed = Vec::new();
        for (index, entry) in inspected.into_iter().enumerate() {
            // A *per-skill* write failure omits that skill and keeps the rest,
            // matching how an inspection failure behaves. The caller's selection
            // policy — fail-closed for explicit, best-effort for Default — then
            // applies uniformly to every reason a skill did not make it.
            match write_wrapper(&skills_dir, &entry, index) {
                Ok(()) => {
                    exposed.push(entry.prepared.namespaced.clone());
                    prepared.push(entry.prepared);
                }
                Err(reason) => {
                    // Remove the partial wrapper so the CLI never sees half a
                    // skill; the root itself stays valid for the others.
                    let wrapper = skills_dir.join(&entry.prepared.name);
                    let _ = std::fs::remove_dir_all(&wrapper);
                    refusals.push(SkillRefusal {
                        name: entry.source_name,
                        reason,
                    });
                }
            }
        }
        exposed.sort();

        if prepared.is_empty() {
            // Every skill failed during the write phase. Drop the root rather
            // than pointing the CLI at an empty plugin.
            drop(guard);
            return Ok(PreparedPlugin {
                plugin: None,
                prepared: Vec::new(),
                refusals,
            });
        }

        Ok(PreparedPlugin {
            plugin: Some(Self { guard, exposed }),
            prepared,
            refusals,
        })
    }

    /// Remove the session root.
    ///
    /// The root is **entirely Tyde-owned**: Tyde created it, wrote every regular
    /// file in it, and created every link in it. So it is removed recursively,
    /// which is the honest contract — there is nothing in there that belongs to
    /// anyone else, and pretending otherwise led to a "left in place" branch
    /// that promised more than it could deliver.
    ///
    /// The safety property that actually matters is narrower and is what the
    /// tests pin: `std::fs::remove_dir_all` **unlinks symlinks rather than
    /// following them**, so removing a root full of links into the user's skill
    /// store cannot touch anything in that store. `cleanup_never_follows_links`,
    /// `dropping_the_plugin_spares_every_canonical_source`, and the
    /// partial-failure and unexpected-entry tests each plant a sentinel behind a
    /// link and assert it survives.
    ///
    /// Idempotent, so the `TempDir` drop that follows an explicit shutdown is a
    /// no-op.
    pub(crate) fn cleanup(&self) -> Result<(), String> {
        let root = self.guard.path();
        if !root.exists() {
            return Ok(());
        }
        std::fs::remove_dir_all(root)
            .map_err(|err| format!("Failed to remove {}: {err}", root.display()))
    }
}

/// Create the private session root, or fail visibly.
///
/// On unix this is a `TempDir` restricted to `0700`. On any other platform Tyde
/// cannot currently prove the root is private or that resource links can be
/// created, so it refuses **before the CLI process starts** rather than
/// materializing a world-readable plugin and hoping. A visible "not supported
/// here" beats a silent insecure fallback.
fn create_private_root(parent: Option<&Path>) -> Result<tempfile::TempDir, String> {
    let guard = tempfile::Builder::new()
        .prefix("tyde-claude-skills-")
        .tempdir_in(
            parent
                .map(Path::to_path_buf)
                .unwrap_or_else(std::env::temp_dir),
        )
        .map_err(|err| format!("Failed to create a private Claude plugin root: {err}"))?;
    restrict_dir(guard.path())?;
    Ok(guard)
}

/// Write one wrapper. Every failure here names a single skill.
fn write_wrapper(
    skills_dir: &Path,
    entry: &InspectedSkill,
    index: usize,
) -> Result<(), String> {
    fail_injection_point(index)?;
    let wrapper = skills_dir.join(&entry.prepared.name);
    create_private_dir(&wrapper)?;
    write_private_file(&wrapper.join("SKILL.md"), &entry.contents)?;
    for (link_name, target) in &entry.resources {
        symlink_path(target, &wrapper.join(link_name))
            .map_err(|err| format!("its resource '{link_name}' could not be linked: {err}"))?;
    }
    Ok(())
}

/// One skill that passed inspection: the bytes to write and the links to make.
struct InspectedSkill {
    prepared: PreparedSkill,
    /// Store directory name, kept so a later failure can name the skill the way
    /// the user knows it rather than by its synthesized wrapper name.
    source_name: String,
    contents: String,
    /// `(link name, target)` for each top-level resource, `SKILL.md` excluded.
    resources: Vec<(String, PathBuf)>,
}

/// Validate one skill and produce the exact `SKILL.md` bytes Claude will load.
///
/// Every reason a skill cannot be exposed is discovered here, before anything is
/// written, so the caller sees a refusal rather than a partially built root.
fn inspect_skill(
    skill: &ResolvedSkill,
    claimed: &mut BTreeSet<String>,
) -> Result<InspectedSkill, String> {
    // One read. These bytes are what gets validated and what gets written, so
    // a later rewrite of the store file cannot change what Claude loads.
    let raw = std::fs::read_to_string(&skill.skill_md_path)
        .map_err(|err| format!("could not read {}: {err}", skill.skill_md_path.display()))?;
    let parsed = parse_skill_md(&raw)?;
    let resources = inspect_resources(skill)?;
    let description = parsed
        .description
        .or_else(|| skill.description.clone())
        .map(|text| collapse_to_one_line(&text))
        .filter(|text| !text.is_empty());
    // Synthesized last, and only for a skill that is otherwise going to be
    // exposed, so a refused skill never consumes an ordinal and the numbering
    // stays a function of what actually materializes.
    let exposed = synthesize_exposed_name(&skill.name, claimed);
    let contents = render_skill_md(&exposed, description.as_deref(), parsed.body);
    Ok(InspectedSkill {
        prepared: PreparedSkill {
            name: exposed.clone(),
            namespaced: namespaced_skill_name(&exposed),
            source_name: skill.name.clone(),
            description,
        },
        source_name: skill.name.clone(),
        contents,
        resources,
    })
}

/// Enumerate and validate the top-level entries that will be linked.
fn inspect_resources(skill: &ResolvedSkill) -> Result<Vec<(String, PathBuf)>, String> {
    let entries = std::fs::read_dir(&skill.source_dir).map_err(|err| {
        format!(
            "could not list its resources at {}: {err}",
            skill.source_dir.display()
        )
    })?;
    let canonical_source = skill
        .source_dir
        .canonicalize()
        .map_err(|err| format!("its directory could not be resolved: {err}"))?;
    let mut resources = Vec::new();
    for entry in entries {
        let entry = entry.map_err(|err| format!("one of its resources could not be read: {err}"))?;
        let file_name = entry.file_name();
        let Some(as_str) = file_name.to_str() else {
            return Err("it has a resource whose name is not valid UTF-8".to_string());
        };
        if as_str == "SKILL.md" {
            // Never linked: the wrapper's SKILL.md is Tyde's inspected snapshot.
            continue;
        }
        if REFUSED_RESOURCE_NAMES.contains(&as_str) {
            return Err(format!(
                "it ships a top-level '{as_str}', which names a plugin activation surface and \
                 must not appear in a Tyde skill wrapper"
            ));
        }
        // Defence in depth: a resource that already escapes its own skill
        // directory is refused rather than linked. The link Tyde creates still
        // resolves at load time, so this narrows the surface without pretending
        // to be a containment proof — only copying would be that.
        let resolved = entry.path().canonicalize().map_err(|err| {
            format!("its resource '{as_str}' could not be resolved: {err}")
        })?;
        if !resolved.starts_with(&canonical_source) {
            return Err(format!(
                "its resource '{as_str}' resolves outside its own directory"
            ));
        }
        // Link the path that was *checked*, not the entry path. `entry.path()`
        // may itself be a symlink, and re-resolving it at link time would mean
        // the wrapper points at whatever it resolves to then rather than at the
        // directory this containment check just approved.
        resources.push((as_str.to_string(), resolved));
    }
    resources.sort();
    Ok(resources)
}

#[cfg(test)]
thread_local! {
    /// Test-only: fail the write phase before the wrapper at this index, to
    /// exercise the rollback path with a real partial write on disk.
    static FAIL_WRITE_AT: std::cell::Cell<Option<usize>> = const { std::cell::Cell::new(None) };
}

#[cfg(test)]
fn fail_injection_point(index: usize) -> Result<(), String> {
    FAIL_WRITE_AT.with(|slot| match slot.get() {
        Some(target) if target == index => Err(format!("injected write failure at {index}")),
        _ => Ok(()),
    })
}

#[cfg(not(test))]
fn fail_injection_point(_index: usize) -> Result<(), String> {
    Ok(())
}

struct ParsedSkillMd<'a> {
    description: Option<String>,
    /// Instructional body, preserved exactly as read.
    body: &'a str,
}

/// Split and validate a `SKILL.md`.
///
/// Fail-closed on malformed frontmatter: an unterminated block, YAML that does
/// not parse, or YAML that is not a mapping is a refusal, not something to
/// guess around. A file with **no** frontmatter at all is fine — 2.1.220 loads
/// one — and its whole content is the body.
fn parse_skill_md(raw: &str) -> Result<ParsedSkillMd<'_>, String> {
    let Some(rest) = strip_frontmatter_open(raw) else {
        return Ok(ParsedSkillMd {
            description: None,
            body: raw,
        });
    };
    let Some((frontmatter, body)) = split_frontmatter_close(rest) else {
        return Err(
            "its SKILL.md opens a '---' frontmatter block that is never closed".to_string(),
        );
    };
    let value: serde_yaml::Value = serde_yaml::from_str(frontmatter)
        .map_err(|err| format!("its SKILL.md frontmatter is not valid YAML: {err}"))?;
    let mapping = match value {
        serde_yaml::Value::Mapping(mapping) => mapping,
        serde_yaml::Value::Null => serde_yaml::Mapping::new(),
        _ => return Err("its SKILL.md frontmatter is not a YAML mapping".to_string()),
    };

    let mut activation = Vec::new();
    let mut unknown = Vec::new();
    let mut description = None;
    for (key, value) in &mapping {
        let Some(key) = key.as_str() else {
            return Err("its SKILL.md frontmatter has a non-string key".to_string());
        };
        let normalized = key.trim().to_ascii_lowercase();
        if ALLOWED_FRONTMATTER_KEYS.contains(&normalized.as_str()) {
            if normalized == "description"
                && let Some(text) = value.as_str()
            {
                description = Some(text.to_string());
            }
            continue;
        }
        if KNOWN_ACTIVATION_KEYS.contains(&normalized.as_str()) {
            activation.push(key.trim().to_string());
        } else {
            unknown.push(key.trim().to_string());
        }
    }
    if !activation.is_empty() || !unknown.is_empty() {
        activation.sort();
        unknown.sort();
        let mut reasons = Vec::new();
        if !activation.is_empty() {
            reasons.push(format!(
                "declares {}, which changes what the skill may do",
                activation.join(", ")
            ));
        }
        if !unknown.is_empty() {
            reasons.push(format!(
                "declares {}, which Tyde cannot prove is inert",
                unknown.join(", ")
            ));
        }
        return Err(format!(
            "its SKILL.md frontmatter {}. Only 'name' and 'description' are carried into a \
             Tyde wrapper; dropping anything else would silently change the skill's behaviour",
            reasons.join(", and ")
        ));
    }
    Ok(ParsedSkillMd { description, body })
}

fn strip_frontmatter_open(raw: &str) -> Option<&str> {
    let raw = raw.strip_prefix('\u{feff}').unwrap_or(raw);
    raw.strip_prefix("---\n")
        .or_else(|| raw.strip_prefix("---\r\n"))
}

fn split_frontmatter_close(rest: &str) -> Option<(&str, &str)> {
    if let Some(index) = rest.find("\n---\n") {
        return Some((&rest[..index], &rest[index + 5..]));
    }
    if let Some(index) = rest.find("\n---\r\n") {
        return Some((&rest[..index], &rest[index + 6..]));
    }
    // A frontmatter block that ends the file with no trailing newline.
    if let Some(frontmatter) = rest.strip_suffix("\n---") {
        return Some((frontmatter, ""));
    }
    None
}

/// Build the sanitized snapshot: synthesized frontmatter plus the body as read.
///
/// `name` must equal the wrapper directory name so Claude addresses the skill as
/// `tyde-skills:<name>` whichever of the two the loader keys on. Both scalars are
/// emitted as YAML double-quoted strings via JSON escaping, which YAML accepts,
/// so no name or description can break out of the block.
///
/// The body is appended **byte for byte**. Nothing is trimmed: leading blank
/// lines, indentation, and trailing whitespace are all part of a Markdown
/// document's meaning, and a wrapper that quietly reflowed a skill would be
/// changing instructions the user wrote.
fn render_skill_md(name: &str, description: Option<&str>, body: &str) -> String {
    let description = description.unwrap_or("A skill installed in Tyde.");
    format!(
        "---\nname: {}\ndescription: {}\n---\n{}",
        yaml_quote(name),
        yaml_quote(description),
        body
    )
}

/// Derive a wrapper name that is safe to use as both a directory name and a
/// plugin-namespaced skill id, and that cannot be confused with another one.
///
/// Source names come from the user's store and are only guaranteed to be
/// directory names. On a case-insensitive or Unicode-normalizing filesystem
/// `Build-Games`, `build-games`, and a decomposed-accent variant can all be the
/// same directory, so using them verbatim would let one wrapper silently
/// overwrite another. Synthesis maps every source name into a restricted ASCII
/// alphabet and disambiguates by **ordinal suffix**, deterministically, in
/// selection order.
///
/// The result is used for the directory, the frontmatter `name`, and the exposed
/// `tyde-skills:<name>` id, so all three agree by construction.
fn synthesize_exposed_name(source: &str, claimed: &mut BTreeSet<String>) -> String {
    let mut base: String = source
        .chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() {
                ch.to_ascii_lowercase()
            } else {
                // Everything else, including `_` and every non-ASCII character,
                // becomes `-`. The alphabet is exactly [a-z0-9-]: anything
                // wider risks a name the CLI, the filesystem, or the namespace
                // treats differently from how Tyde does.
                '-'
            }
        })
        .collect();
    while base.contains("--") {
        base = base.replace("--", "-");
    }
    base = base.trim_matches('-').to_string();
    if base.is_empty() || base.starts_with(|ch: char| ch.is_ascii_digit()) {
        base = format!("skill-{base}");
        base = base.trim_end_matches('-').to_string();
    }
    base = truncate_to_limit(&base, EXPOSED_NAME_MAX_LEN);
    if claimed.insert(base.clone()) {
        return base;
    }
    // Deterministic: the second `build-games` becomes `build-games-2`, the
    // third `build-games-3`, in the order the selection listed them. The suffix
    // is part of the budget, so a name at the limit is shortened to make room
    // rather than pushed over it.
    for ordinal in 2u32.. {
        let suffix = format!("-{ordinal}");
        let room = EXPOSED_NAME_MAX_LEN.saturating_sub(suffix.len());
        let candidate = format!("{}{suffix}", truncate_to_limit(&base, room));
        if claimed.insert(candidate.clone()) {
            return candidate;
        }
    }
    unreachable!("an ordinal suffix always terminates")
}

fn yaml_quote(value: &str) -> String {
    serde_json::to_string(value).unwrap_or_else(|_| "\"\"".to_string())
}

fn collapse_to_one_line(text: &str) -> String {
    text.split_whitespace().collect::<Vec<_>>().join(" ")
}

/// Cut to `limit` characters without leaving a trailing separator.
fn truncate_to_limit(value: &str, limit: usize) -> String {
    if value.len() <= limit {
        return value.to_string();
    }
    let cut = value[..limit].trim_end_matches('-').to_string();
    if cut.is_empty() { "skill".to_string() } else { cut }
}

/// Minimal manifest. `skills` is deliberately absent: declaring it shadows the
/// auto-loaded `skills/` folder and turns manifest-relative paths into a
/// traversal check, which breaks resource resolution.
fn plugin_manifest_json() -> String {
    format!(
        "{{\n  \"name\": \"{TYDE_SKILLS_PLUGIN_NAME}\",\n  \
         \"description\": \"Skills installed in Tyde\",\n  \
         \"version\": \"0.0.0\"\n}}\n"
    )
}

pub(crate) fn namespaced_skill_name(name: &str) -> String {
    format!("{TYDE_SKILLS_PLUGIN_NAME}:{name}")
}

/// Does this CLI's `--help` advertise plugin sideloading?
pub(crate) fn help_text_supports_plugin_dir(help: &str) -> bool {
    help.contains(CLAUDE_PLUGIN_DIR_FLAG)
}

/// Error for a CLI that cannot sideload a plugin. Names the flag rather than a
/// version: one installed CLI cannot establish a floor version, and a wrong
/// version number in an error message is worse than none.
pub(crate) fn unsupported_plugin_dir_error() -> String {
    format!(
        "This Claude CLI does not support `{CLAUDE_PLUGIN_DIR_FLAG}`, so Tyde cannot expose \
         installed skills to it. Skills are discovered natively from a session-scoped \
         `{TYDE_SKILLS_PLUGIN_NAME}` plugin; Tyde will not fall back to pasting skill bodies \
         into the prompt. Upgrade the Claude CLI, or remove Tyde skills from this agent to \
         start without them."
    )
}

/// Verify `claude plugin list --json` output against the root Tyde built.
///
/// This is the **stable machine-readable** surface, and it is the only one:
/// `plugin list --json` is a documented flag emitting a JSON array with `id`,
/// `enabled`, and `installPath`. It proves the CLI accepted `--plugin-dir`, read
/// the manifest, and enabled the plugin — every *global* failure mode — at zero
/// provider cost, before the session process starts.
///
/// It deliberately does **not** enumerate skills. `plugin details` does, but only
/// as human-readable text (`Skills (2)  a, b`) with no documented format and no
/// `--json`, and `plugin validate --strict` prints "Validation failed" while
/// exiting 0. Parsing either would be building a gate on an unstable surface, so
/// per-skill verification is left to the `init`-frame consistency check.
pub(crate) fn verify_plugin_inventory(output: &str, expected_root: &Path) -> Result<(), String> {
    let parsed: serde_json::Value = serde_json::from_str(output).map_err(|err| {
        format!(
            "Claude's plugin inventory was not valid JSON, so Tyde cannot confirm the session \
             plugin loaded: {err}"
        )
    })?;
    let entries = parsed.as_array().ok_or_else(|| {
        "Claude's plugin inventory was not a JSON array, so Tyde cannot confirm the session \
         plugin loaded"
            .to_string()
    })?;
    let expected_id = format!("{TYDE_SKILLS_PLUGIN_NAME}@inline");
    let matching: Vec<&serde_json::Value> = entries
        .iter()
        .filter(|entry| entry.get("id").and_then(|id| id.as_str()) == Some(expected_id.as_str()))
        .collect();
    // More than one entry under our id means the CLI resolved the name from two
    // places. Which one carries this session's skills is then a guess, and a
    // guess is exactly what this check exists to remove.
    if matching.len() > 1 {
        return Err(format!(
            "Claude reported {} plugins under the id '{expected_id}', so Tyde cannot tell \
             which one this session's skills came from",
            matching.len()
        ));
    }
    let entry = matching.first().ok_or_else(|| {
        format!(
            "Claude did not load the '{expected_id}' plugin from {}, so this session's skills \
             would be missing",
            expected_root.display()
        )
    })?;
    if entry.get("enabled").and_then(serde_json::Value::as_bool) != Some(true) {
        return Err(format!(
            "Claude loaded '{expected_id}' but reported it as disabled, so this session's \
             skills would be unavailable"
        ));
    }
    // A non-empty `errors` array means the CLI took the plugin but had
    // complaints about it. Whatever it could not process is precisely what
    // would go missing later, so this is a startup failure rather than a note.
    if let Some(errors) = entry.get("errors").and_then(serde_json::Value::as_array)
        && !errors.is_empty()
    {
        let rendered = errors
            .iter()
            .map(|error| {
                error
                    .as_str()
                    .map(str::to_string)
                    .unwrap_or_else(|| error.to_string())
            })
            .collect::<Vec<_>>()
            .join("; ");
        return Err(format!(
            "Claude reported {} problem(s) loading '{expected_id}': {rendered}",
            errors.len()
        ));
    }
    let reported = entry
        .get("installPath")
        .and_then(|path| path.as_str())
        .ok_or_else(|| {
            format!(
                "Claude reported '{expected_id}' without an install path, so Tyde cannot \
                 confirm it loaded this session's root"
            )
        })?;
    // Exact canonical equality, and both sides must canonicalize. TMPDIR is a
    // symlink on macOS, so the CLI may echo `/tmp/...` where Tyde holds
    // `/private/tmp/...`; resolving both is the only correct comparison, and a
    // path that will not resolve is a failure rather than something to fall
    // back from.
    let reported_canonical = std::fs::canonicalize(reported).map_err(|err| {
        format!(
            "Claude reported '{expected_id}' at {reported}, which Tyde could not resolve: {err}"
        )
    })?;
    let expected_canonical = std::fs::canonicalize(expected_root).map_err(|err| {
        format!(
            "Tyde could not resolve this session's plugin root {}: {err}",
            expected_root.display()
        )
    })?;
    if reported_canonical != expected_canonical {
        return Err(format!(
            "Claude loaded '{expected_id}' from {}, not from this session's root {}",
            reported_canonical.display(),
            expected_canonical.display()
        ));
    }
    Ok(())
}

/// Result of checking a CLI `init` frame against what Tyde materialized.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) enum InitFrameVerdict {
    Verified,
    Failed(String),
}

/// Verify that every materialized skill was loaded, exactly once.
///
/// `reported` is the `init` frame's `skills` array; `None` means the frame did
/// not carry the field. Both a missing field and a missing skill are failures:
/// starting a turn believing a skill is available when it is not is the failure
/// mode this whole design exists to prevent.
pub(crate) fn verify_init_frame(
    expected: &[String],
    reported: Option<&[String]>,
) -> InitFrameVerdict {
    if expected.is_empty() {
        return InitFrameVerdict::Verified;
    }
    let Some(reported) = reported else {
        return InitFrameVerdict::Failed(
            "Claude's init frame did not report a 'skills' field, so Tyde cannot confirm the \
             session's skills were loaded"
                .to_string(),
        );
    };

    let mut counts: BTreeMap<&str, usize> = BTreeMap::new();
    for name in reported {
        *counts.entry(name.as_str()).or_default() += 1;
    }

    let duplicated: Vec<&str> = expected
        .iter()
        .map(String::as_str)
        .filter(|name| counts.get(name).copied().unwrap_or(0) > 1)
        .collect();
    if !duplicated.is_empty() {
        return InitFrameVerdict::Failed(format!(
            "Claude reported {} more than once, so the '{TYDE_SKILLS_PLUGIN_NAME}' namespace \
             collides with another loaded skill",
            duplicated.join(", ")
        ));
    }

    let missing: Vec<&str> = expected
        .iter()
        .map(String::as_str)
        .filter(|name| !counts.contains_key(name))
        .collect();
    if !missing.is_empty() {
        return InitFrameVerdict::Failed(format!(
            "Claude did not load {}. The most likely cause is a name collision with a skill \
             already installed in Claude, which Claude resolves in favour of its own copy. \
             Rename the Tyde skill, or remove it from this agent.",
            missing.join(", ")
        ));
    }
    InitFrameVerdict::Verified
}

/// The steering overlay describing how to reach Tyde skills.
///
/// Built **only from skills that were actually materialized**, so the model is
/// never told about a skill the session failed to expose. `AllInstalled` gets one
/// constant-size paragraph and no enumeration: Claude's own listing already
/// carries every name and description, and re-listing them would rebuild the
/// duplication this work removes. `Explicit` enumerates, because a custom
/// agent's selection is a deliberate statement of intent. Neither carries a body.
pub(crate) fn native_skill_overlay(selection: SkillSelection, prepared: &[PreparedSkill]) -> String {
    match selection {
        SkillSelection::AllInstalled => format!(
            "Skills installed in Tyde are available through the \
             `{TYDE_SKILLS_PLUGIN_NAME}` plugin and are addressed as \
             `{TYDE_SKILLS_PLUGIN_NAME}:<name>`. Their names and descriptions \
             are already listed among your available skills; read a skill only \
             when you invoke it."
        ),
        SkillSelection::Explicit => {
            let mut lines = vec![format!(
                "This agent selected these Tyde skills, available through the \
                 `{TYDE_SKILLS_PLUGIN_NAME}` plugin as `{TYDE_SKILLS_PLUGIN_NAME}:<name>`:"
            )];
            for skill in prepared {
                // Show the store name too when synthesis renamed the skill, so
                // the id the model uses is never a mystery.
                let label = if skill.name == skill.source_name {
                    skill.name.clone()
                } else {
                    format!("{} (installed as '{}')", skill.name, skill.source_name)
                };
                match skill.description.as_deref() {
                    Some(description) if !description.is_empty() => {
                        lines.push(format!("- {label} — {description}"));
                    }
                    _ => lines.push(format!("- {label}")),
                }
            }
            lines.join("\n")
        }
    }
}

/// User-visible notice for a Default session that started without some skills.
pub(crate) fn degraded_default_notice(refusals: &[SkillRefusal]) -> String {
    let mut lines = vec![format!(
        "Tyde started this Claude session without {} installed skill(s):",
        refusals.len()
    )];
    for refusal in refusals {
        lines.push(format!("- {}", refusal.describe()));
    }
    lines.push(
        "The rest of the session's skills are available normally. Fix or remove the skills above \
         to expose them."
            .to_string(),
    );
    lines.join("\n")
}

fn create_private_dir(path: &Path) -> Result<(), String> {
    std::fs::create_dir_all(path)
        .map_err(|err| format!("Failed to create {}: {err}", path.display()))?;
    restrict_dir(path)
}

fn write_private_file(path: &Path, contents: &str) -> Result<(), String> {
    std::fs::write(path, contents)
        .map_err(|err| format!("Failed to write {}: {err}", path.display()))?;
    restrict_file(path)
}

#[cfg(unix)]
fn restrict_dir(path: &Path) -> Result<(), String> {
    use std::os::unix::fs::PermissionsExt;
    std::fs::set_permissions(path, std::fs::Permissions::from_mode(0o700))
        .map_err(|err| format!("Failed to restrict {}: {err}", path.display()))
}

#[cfg(unix)]
fn restrict_file(path: &Path) -> Result<(), String> {
    use std::os::unix::fs::PermissionsExt;
    std::fs::set_permissions(path, std::fs::Permissions::from_mode(0o600))
        .map_err(|err| format!("Failed to restrict {}: {err}", path.display()))
}

/// On a platform where Tyde cannot make the root private, refuse.
///
/// These are deliberately hard errors rather than no-ops. A no-op would leave a
/// plugin root containing the user's skill instructions readable by every other
/// account on the machine, and would do so silently. Failing here happens
/// **before the CLI process starts**, so the session reports "skills are not
/// supported on this platform" instead of quietly running insecurely.
#[cfg(not(unix))]
fn restrict_dir(path: &Path) -> Result<(), String> {
    Err(unsupported_platform_error(path))
}

#[cfg(not(unix))]
fn restrict_file(path: &Path) -> Result<(), String> {
    Err(unsupported_platform_error(path))
}

#[cfg(not(unix))]
fn unsupported_platform_error(path: &Path) -> String {
    format!(
        "Tyde cannot create a private Claude plugin root at {} on this platform: restricting \
         it to the current user is not implemented here, and Tyde will not materialize skill \
         instructions into a world-readable directory. Claude skills are unavailable until \
         this platform gains a secure temporary-directory path.",
        path.display()
    )
}

#[cfg(unix)]
fn symlink_path(target: &Path, link: &Path) -> std::io::Result<()> {
    std::os::unix::fs::symlink(target, link)
}

#[cfg(windows)]
fn symlink_path(target: &Path, link: &Path) -> std::io::Result<()> {
    if target.is_dir() {
        std::os::windows::fs::symlink_dir(target, link)
    } else {
        std::os::windows::fs::symlink_file(target, link)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use protocol::SkillId;

    fn store_skill(store: &Path, name: &str, skill_md: &str) -> ResolvedSkill {
        let dir = store.join(name);
        std::fs::create_dir_all(&dir).expect("create skill dir");
        let skill_md_path = dir.join("SKILL.md");
        std::fs::write(&skill_md_path, skill_md).expect("write SKILL.md");
        ResolvedSkill::path_only(
            protocol::Skill {
                id: SkillId(name.to_string()),
                name: name.to_string(),
                title: None,
                description: Some(format!("{name} description")),
            },
            dir,
            skill_md_path,
        )
    }

    fn prepare_ok(parent: &Path, skills: &[ResolvedSkill]) -> ClaudeSkillPlugin {
        let outcome = ClaudeSkillPlugin::prepare(Some(parent), skills).expect("prepare");
        assert!(outcome.refusals.is_empty(), "{:?}", outcome.refusals);
        outcome.plugin.expect("a plugin")
    }

    #[test]
    fn skill_md_is_a_sanitized_snapshot_not_a_link_to_the_store() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let store = tmp.path().join("store");
        let skills = vec![store_skill(
            &store,
            "alpha",
            "---\nname: something-else\ndescription: Original text.\n---\n\nBODY-11aa22\n",
        )];

        let plugin = prepare_ok(tmp.path(), &skills);
        let wrapper_md = plugin.root().join("skills").join("alpha").join("SKILL.md");

        assert!(
            std::fs::symlink_metadata(&wrapper_md)
                .expect("metadata")
                .file_type()
                .is_file(),
            "SKILL.md must be a real file Tyde wrote, never a link into the store"
        );
        let written = std::fs::read_to_string(&wrapper_md).expect("read snapshot");
        assert!(
            written.starts_with("---\nname: \"alpha\"\n"),
            "the snapshot's name must match the wrapper directory: {written}"
        );
        assert!(written.contains("description: \"Original text.\""), "{written}");
        assert!(
            !written.contains("something-else"),
            "the snapshot's name is the wrapper name, not whatever the store claimed: {written}"
        );
        assert!(written.contains("BODY-11aa22"), "the body is preserved: {written}");
    }

    #[test]
    fn a_store_rewrite_after_inspection_cannot_change_what_claude_loads() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let store = tmp.path().join("store");
        let skills = vec![store_skill(
            &store,
            "alpha",
            "---\nname: alpha\ndescription: Safe.\n---\n\nSAFE-BODY\n",
        )];
        let plugin = prepare_ok(tmp.path(), &skills);

        // The store file is swapped for one that would have been refused.
        std::fs::write(
            &skills[0].skill_md_path,
            "---\nname: alpha\nhooks:\n  - evil\n---\n\nEVIL-BODY\n",
        )
        .expect("rewrite store SKILL.md");

        let loaded = std::fs::read_to_string(plugin.root().join("skills").join("alpha").join("SKILL.md"))
            .expect("read snapshot");
        assert!(loaded.contains("SAFE-BODY"), "{loaded}");
        assert!(
            !loaded.contains("EVIL-BODY") && !loaded.contains("hooks"),
            "the inspected bytes are what Claude loads: {loaded}"
        );
    }

    #[test]
    fn resources_are_linked_so_relative_paths_resolve() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let store = tmp.path().join("store");
        let skills = vec![store_skill(&store, "guide", "---\nname: guide\n---\nsee art.md\n")];
        std::fs::write(store.join("guide").join("art.md"), "RES-9f8e7d").expect("resource");
        std::fs::create_dir_all(store.join("guide").join("scripts")).expect("scripts dir");
        std::fs::write(store.join("guide").join("scripts").join("run.sh"), "echo hi")
            .expect("script");

        let plugin = prepare_ok(tmp.path(), &skills);
        let wrapper = plugin.root().join("skills").join("guide");

        assert_eq!(
            std::fs::read_to_string(wrapper.join("art.md")).expect("read through link"),
            "RES-9f8e7d"
        );
        assert_eq!(
            std::fs::read_to_string(wrapper.join("scripts").join("run.sh")).expect("nested"),
            "echo hi",
            "a linked resource directory keeps its whole subtree reachable"
        );
        assert!(
            std::fs::symlink_metadata(wrapper.join("art.md"))
                .expect("metadata")
                .file_type()
                .is_symlink(),
            "resources are linked, not copied"
        );
    }

    #[test]
    fn malformed_frontmatter_is_refused_fail_closed() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let store = tmp.path().join("store");
        for (name, body, expected) in [
            ("unterminated", "---\nname: x\nbody with no close\n", "never closed"),
            ("badyaml", "---\n\tname: [unclosed\n---\nbody\n", "not valid YAML"),
            ("scalar", "---\njust a string\n---\nbody\n", "not a YAML mapping"),
        ] {
            let skills = vec![store_skill(&store, name, body)];
            let outcome = ClaudeSkillPlugin::prepare(Some(tmp.path()), &skills).expect("prepare");
            assert!(outcome.plugin.is_none(), "{name} must not materialize");
            assert_eq!(outcome.refusals.len(), 1, "{:?}", outcome.refusals);
            assert!(
                outcome.refusals[0].reason.contains(expected),
                "{name}: {:?}",
                outcome.refusals[0]
            );
        }
    }

    #[test]
    fn activation_frontmatter_is_refused_and_named() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let store = tmp.path().join("store");
        let skills = vec![
            store_skill(&store, "inert", "---\nname: inert\ndescription: d\n---\nbody\n"),
            store_skill(&store, "hooky", "---\nname: hooky\nHooks:\n  - x\n---\nbody\n"),
            store_skill(&store, "serverish", "---\nname: s\nmcpServers:\n  x: {}\n---\nbody\n"),
        ];

        let outcome = ClaudeSkillPlugin::prepare(Some(tmp.path()), &skills).expect("prepare");

        let plugin = outcome.plugin.expect("the inert skill materializes");
        assert_eq!(plugin.exposed(), ["tyde-skills:inert"]);
        assert_eq!(outcome.refusals.len(), 2, "{:?}", outcome.refusals);
        assert!(outcome.refusals.iter().any(|r| r.name == "hooky" && r.reason.contains("Hooks")));
        assert!(
            outcome.refusals.iter().any(|r| r.name == "serverish" && r.reason.contains("mcpServers"))
        );
        assert!(!plugin.root().join("skills").join("hooky").exists());
    }

    #[test]
    fn a_skill_without_frontmatter_gets_synthesized_frontmatter() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let store = tmp.path().join("store");
        let skills = vec![store_skill(&store, "bare", "Just instructions.\n")];

        let plugin = prepare_ok(tmp.path(), &skills);

        let written =
            std::fs::read_to_string(plugin.root().join("skills").join("bare").join("SKILL.md"))
                .expect("snapshot");
        assert!(written.starts_with("---\nname: \"bare\"\n"), "{written}");
        assert!(written.contains("description: \"bare description\""), "{written}");
        assert!(written.contains("Just instructions."), "{written}");
    }

    #[test]
    fn a_name_that_could_break_out_of_yaml_is_quoted_or_refused() {
        assert_eq!(yaml_quote("a\"b"), "\"a\\\"b\"");
        assert_eq!(yaml_quote("line\nbreak"), "\"line\\nbreak\"");
        let rendered = render_skill_md("ok", Some("has: colon and \"quotes\""), "body\n");
        assert!(
            rendered.contains("description: \"has: colon and \\\"quotes\\\"\""),
            "{rendered}"
        );
    }

    #[test]
    fn a_resource_naming_an_activation_surface_refuses_the_skill() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let store = tmp.path().join("store");
        let skills = vec![
            store_skill(&store, "ok", "---\nname: ok\n---\nbody\n"),
            store_skill(&store, "sneaky", "---\nname: sneaky\n---\nbody\n"),
        ];
        std::fs::write(store.join("sneaky").join(".mcp.json"), "{}").expect("mcp file");

        let outcome = ClaudeSkillPlugin::prepare(Some(tmp.path()), &skills).expect("prepare");

        let plugin = outcome.plugin.expect("the clean skill still materializes");
        assert_eq!(plugin.exposed(), ["tyde-skills:ok"]);
        assert_eq!(outcome.refusals.len(), 1, "{:?}", outcome.refusals);
        assert_eq!(outcome.refusals[0].name, "sneaky");
        assert!(outcome.refusals[0].reason.contains(".mcp.json"), "{:?}", outcome.refusals[0]);
    }

    #[test]
    fn a_resource_escaping_its_skill_directory_refuses_the_skill() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let store = tmp.path().join("store");
        let outside = tmp.path().join("outside");
        std::fs::create_dir_all(&outside).expect("outside dir");
        std::fs::write(outside.join("secret.txt"), "secret").expect("secret");
        let skills = vec![store_skill(&store, "escaper", "---\nname: escaper\n---\nbody\n")];
        symlink_path(&outside.join("secret.txt"), &store.join("escaper").join("leak.txt"))
            .expect("escaping resource");

        let outcome = ClaudeSkillPlugin::prepare(Some(tmp.path()), &skills).expect("prepare");

        assert!(outcome.plugin.is_none());
        assert_eq!(outcome.refusals.len(), 1, "{:?}", outcome.refusals);
        assert!(
            outcome.refusals[0].reason.contains("outside its own directory"),
            "{:?}",
            outcome.refusals[0]
        );
    }

    #[test]
    fn unsafe_source_names_are_synthesized_not_refused() {
        let mut claimed = BTreeSet::new();
        assert_eq!(synthesize_exposed_name("build-games", &mut claimed), "build-games");
        assert_eq!(synthesize_exposed_name("build:games", &mut claimed), "build-games-2");
        assert_eq!(synthesize_exposed_name(".hidden", &mut claimed), "hidden");
        assert_eq!(synthesize_exposed_name("nested/skill", &mut claimed), "nested-skill");
        assert_eq!(synthesize_exposed_name("..", &mut claimed), "skill");
        assert_eq!(synthesize_exposed_name("", &mut claimed), "skill-2");
        assert_eq!(synthesize_exposed_name("Ünïcødé Skîll", &mut claimed), "n-c-d-sk-ll");
        assert_eq!(synthesize_exposed_name("2fast", &mut claimed), "skill-2fast");
    }

    #[test]
    fn case_and_unicode_equivalent_names_cannot_overwrite_each_other() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let store = tmp.path().join("store");
        // On a case-insensitive filesystem these three source directories would
        // collapse onto one wrapper if the source name were used verbatim.
        let skills = vec![
            store_skill(&store, "Alpha", "---\nname: Alpha\n---\nFIRST\n"),
            store_skill(&store, "alpha", "---\nname: alpha\n---\nSECOND\n"),
            store_skill(&store, "ALPHA", "---\nname: ALPHA\n---\nTHIRD\n"),
        ];

        let outcome = ClaudeSkillPlugin::prepare(Some(tmp.path()), &skills).expect("prepare");

        let plugin = outcome.plugin.expect("a plugin");
        assert!(outcome.refusals.is_empty(), "{:?}", outcome.refusals);
        assert_eq!(
            plugin.exposed(),
            ["tyde-skills:alpha", "tyde-skills:alpha-2", "tyde-skills:alpha-3"],
            "each source must get its own exposed name"
        );
        // Every body survived: nothing was overwritten.
        let read = |name: &str| {
            std::fs::read_to_string(plugin.root().join("skills").join(name).join("SKILL.md"))
                .expect("snapshot")
        };
        assert!(read("alpha").contains("FIRST"));
        assert!(read("alpha-2").contains("SECOND"));
        assert!(read("alpha-3").contains("THIRD"));
        assert_eq!(
            outcome.prepared.iter().map(|s| s.source_name.as_str()).collect::<Vec<_>>(),
            ["Alpha", "alpha", "ALPHA"],
            "the store name each wrapper came from is retained"
        );
    }

    #[test]
    fn exposed_names_stay_within_the_documented_alphabet_and_length() {
        let mut claimed = BTreeSet::new();
        let cases = [
            "under_score_name",
            "Ünïcødé Skîll",
            "MiXeD-CaSe",
            "trailing---dashes---",
            &"x".repeat(200),
            &format!("{}-tail", "y".repeat(70)),
        ];
        for case in cases {
            let name = synthesize_exposed_name(case, &mut claimed);
            assert!(
                name.chars().all(|ch| ch.is_ascii_lowercase() || ch.is_ascii_digit() || ch == '-'),
                "{case:?} produced {name:?}, outside [a-z0-9-]"
            );
            assert!(name.len() <= 64, "{case:?} produced {} chars", name.len());
            assert!(!name.is_empty() && !name.starts_with('-') && !name.ends_with('-'), "{name:?}");
            assert!(!name.contains("--"), "{name:?}");
        }
        assert_eq!(synthesize_exposed_name("under_score", &mut claimed), "under-score");
    }

    #[test]
    fn a_collision_between_long_names_still_fits_the_limit() {
        let mut claimed = BTreeSet::new();
        let long = "z".repeat(200);
        let first = synthesize_exposed_name(&long, &mut claimed);
        let second = synthesize_exposed_name(&long, &mut claimed);
        let third = synthesize_exposed_name(&long, &mut claimed);

        assert_eq!(first.len(), 64);
        assert_ne!(first, second);
        assert_ne!(second, third);
        for name in [&second, &third] {
            assert!(name.len() <= 64, "{name:?} is {} chars", name.len());
            assert!(!name.ends_with('-'), "{name:?}");
        }
        assert!(second.ends_with("-2") && third.ends_with("-3"), "{second:?} {third:?}");
    }

    #[test]
    fn a_resource_link_points_at_the_canonical_target_that_was_checked() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let store = tmp.path().join("store");
        let skills = vec![store_skill(&store, "alpha", "---\nname: alpha\n---\nbody\n")];
        let real = store.join("alpha").join("real.txt");
        std::fs::write(&real, "ORIGINAL").expect("real resource");
        // The store entry is itself a link to the real file, inside the skill.
        symlink_path(&real, &store.join("alpha").join("via-link.txt")).expect("entry link");

        let plugin = prepare_ok(tmp.path(), &skills);
        let wrapper_link = plugin.root().join("skills").join("alpha").join("via-link.txt");
        assert_eq!(
            std::fs::read_link(&wrapper_link).expect("wrapper link target"),
            real.canonicalize().expect("canonical real"),
            "the wrapper must link the canonical target that containment approved"
        );

        // Re-point the store's entry at something else. The wrapper still reads
        // the file Tyde checked, because it never depended on that entry.
        let elsewhere = tmp.path().join("elsewhere.txt");
        std::fs::write(&elsewhere, "SWAPPED").expect("elsewhere");
        std::fs::remove_file(store.join("alpha").join("via-link.txt")).expect("unlink");
        symlink_path(&elsewhere, &store.join("alpha").join("via-link.txt")).expect("re-point");

        assert_eq!(
            std::fs::read_to_string(&wrapper_link).expect("read through wrapper link"),
            "ORIGINAL",
            "re-pointing the store entry must not change what the wrapper resolves to"
        );
    }

    #[test]
    fn ordinal_assignment_is_deterministic_in_selection_order() {
        let mut first = BTreeSet::new();
        let mut second = BTreeSet::new();
        for claimed in [&mut first, &mut second] {
            assert_eq!(synthesize_exposed_name("dup", claimed), "dup");
            assert_eq!(synthesize_exposed_name("DUP", claimed), "dup-2");
            assert_eq!(synthesize_exposed_name("d.u.p", claimed), "d-u-p");
        }
        assert_eq!(first, second, "the same selection must produce the same names");
    }

    #[test]
    fn an_unknown_frontmatter_field_is_refused_rather_than_silently_dropped() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let store = tmp.path().join("store");
        let skills = vec![
            store_skill(&store, "plain", "---\nname: plain\ndescription: d\n---\nbody\n"),
            store_skill(
                &store,
                "gated",
                "---\nname: gated\nallowed-tools: [Bash]\n---\nbody\n",
            ),
            store_skill(
                &store,
                "novel",
                "---\nname: novel\nsome-future-field: true\n---\nbody\n",
            ),
        ];

        let outcome = ClaudeSkillPlugin::prepare(Some(tmp.path()), &skills).expect("prepare");

        let plugin = outcome.plugin.expect("the plain skill materializes");
        assert_eq!(plugin.exposed(), ["tyde-skills:plain"]);
        assert_eq!(outcome.refusals.len(), 2, "{:?}", outcome.refusals);
        let gated = outcome.refusals.iter().find(|r| r.name == "gated").expect("gated");
        assert!(
            gated.reason.contains("allowed-tools") && gated.reason.contains("changes what"),
            "{gated:?}"
        );
        let novel = outcome.refusals.iter().find(|r| r.name == "novel").expect("novel");
        assert!(
            novel.reason.contains("some-future-field") && novel.reason.contains("cannot prove"),
            "a field Tyde has never heard of must be refused, not dropped: {novel:?}"
        );
    }

    #[test]
    fn every_skill_refused_yields_no_root_at_all() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let store = tmp.path().join("store");
        let skills = vec![store_skill(&store, "hooky", "---\nname: x\nhooks:\n  - y\n---\nb\n")];

        let outcome = ClaudeSkillPlugin::prepare(Some(tmp.path()), &skills).expect("prepare");

        assert!(outcome.plugin.is_none());
        assert!(outcome.prepared.is_empty());
        assert_eq!(outcome.refusals.len(), 1);
        let leftovers: Vec<_> = std::fs::read_dir(tmp.path())
            .expect("scan parent")
            .flatten()
            .filter(|entry| {
                entry.file_name().to_string_lossy().starts_with("tyde-claude-skills-")
            })
            .collect();
        assert!(leftovers.is_empty(), "no root may be created when nothing survives");
    }

    #[test]
    fn an_unreadable_skill_md_is_refused_not_guessed() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let store = tmp.path().join("store");
        let skill = store_skill(&store, "gone", "---\nname: gone\n---\nbody\n");
        std::fs::remove_file(&skill.skill_md_path).expect("remove SKILL.md");

        let outcome = ClaudeSkillPlugin::prepare(Some(tmp.path()), &[skill]).expect("prepare");

        assert!(outcome.plugin.is_none());
        assert_eq!(outcome.refusals.len(), 1);
        assert!(outcome.refusals[0].reason.contains("could not read"));
    }

    #[cfg(unix)]
    #[test]
    fn the_root_and_its_files_are_private() {
        use std::os::unix::fs::PermissionsExt;
        let tmp = tempfile::tempdir().expect("tempdir");
        let store = tmp.path().join("store");
        let skills = vec![store_skill(&store, "alpha", "---\nname: alpha\n---\nbody\n")];

        let plugin = prepare_ok(tmp.path(), &skills);

        let mode = |path: &Path| {
            std::fs::metadata(path).expect("metadata").permissions().mode() & 0o777
        };
        assert_eq!(mode(plugin.root()), 0o700, "the session root must be private");
        assert_eq!(mode(&plugin.root().join("skills")), 0o700);
        assert_eq!(mode(&plugin.root().join("skills").join("alpha")), 0o700);
        assert_eq!(
            mode(&plugin.root().join("skills").join("alpha").join("SKILL.md")),
            0o600,
            "the generated snapshot must not be world-readable"
        );
        assert_eq!(
            mode(&plugin.root().join(".claude-plugin").join("plugin.json")),
            0o600
        );
    }

    /// Plant a sentinel behind a linked resource directory. Every cleanup path
    /// below asserts it survives, which is the property that actually matters:
    /// removing a root full of links must never reach the user's skill store.
    fn store_with_sentinel(tmp: &Path) -> (Vec<ResolvedSkill>, PathBuf) {
        let store = tmp.join("store");
        let skills = vec![store_skill(&store, "alpha", "---\nname: alpha\n---\nbody\n")];
        let assets = store.join("alpha").join("assets");
        std::fs::create_dir_all(&assets).expect("assets dir");
        let sentinel = assets.join("keep.txt");
        std::fs::write(&sentinel, "SENTINEL").expect("sentinel");
        (skills, sentinel)
    }

    fn sentinel_survives(sentinel: &Path) {
        assert_eq!(
            std::fs::read_to_string(sentinel).expect("the canonical source must survive"),
            "SENTINEL"
        );
    }

    #[test]
    fn a_per_skill_write_failure_omits_only_that_skill() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let store = tmp.path().join("store");
        let skills = vec![
            store_skill(&store, "first", "---\nname: first\n---\nbody\n"),
            store_skill(&store, "second", "---\nname: second\n---\nbody\n"),
            store_skill(&store, "third", "---\nname: third\n---\nbody\n"),
        ];
        // Fail the middle wrapper, after the root and the first are on disk.
        FAIL_WRITE_AT.with(|slot| slot.set(Some(1)));
        let outcome = ClaudeSkillPlugin::prepare(Some(tmp.path()), &skills);
        FAIL_WRITE_AT.with(|slot| slot.set(None));

        let outcome = outcome.expect("a per-skill write failure is not a global failure");
        let plugin = outcome.plugin.expect("the other skills still materialize");
        assert_eq!(
            plugin.exposed(),
            ["tyde-skills:first", "tyde-skills:third"],
            "only the failing skill is omitted"
        );
        assert_eq!(outcome.refusals.len(), 1, "{:?}", outcome.refusals);
        assert_eq!(outcome.refusals[0].name, "second");
        assert!(
            !plugin.root().join("skills").join("second").exists(),
            "a partial wrapper must not be left for the CLI to load"
        );
    }

    #[test]
    fn a_root_with_no_surviving_skill_is_dropped_entirely() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let (skills, sentinel) = store_with_sentinel(tmp.path());
        // Failing the only skill leaves no wrapper, so no root is handed back.
        FAIL_WRITE_AT.with(|slot| slot.set(Some(0)));
        let outcome = ClaudeSkillPlugin::prepare(Some(tmp.path()), &skills);
        FAIL_WRITE_AT.with(|slot| slot.set(None));

        let outcome = outcome.expect("prepare");
        assert!(outcome.plugin.is_none(), "an empty root is never handed back");
        assert_eq!(outcome.refusals.len(), 1);
        let leftovers: Vec<_> = std::fs::read_dir(tmp.path())
            .expect("scan parent")
            .flatten()
            .filter(|entry| {
                entry
                    .file_name()
                    .to_string_lossy()
                    .starts_with("tyde-claude-skills-")
            })
            .collect();
        assert!(leftovers.is_empty(), "the root must be dropped, found {leftovers:?}");
        sentinel_survives(&sentinel);
    }

    #[test]
    fn cleanup_never_follows_links() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let (skills, sentinel) = store_with_sentinel(tmp.path());

        let plugin = prepare_ok(tmp.path(), &skills);
        let root = plugin.root().to_path_buf();
        // The wrapper really does reach the sentinel through a directory link.
        assert_eq!(
            std::fs::read_to_string(
                root.join("skills").join("alpha").join("assets").join("keep.txt")
            )
            .expect("reachable through the link"),
            "SENTINEL"
        );

        plugin.cleanup().expect("cleanup");

        assert!(!root.exists(), "the Tyde-owned root is removed whole");
        sentinel_survives(&sentinel);
        assert!(skills[0].skill_md_path.exists(), "the store SKILL.md survives");
    }

    #[test]
    fn dropping_the_plugin_spares_every_canonical_source() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let (skills, sentinel) = store_with_sentinel(tmp.path());

        let root = {
            let plugin = prepare_ok(tmp.path(), &skills);
            plugin.root().to_path_buf()
        };

        assert!(!root.exists(), "Drop removes the root");
        sentinel_survives(&sentinel);
    }

    #[test]
    fn cleanup_is_idempotent_and_survives_unexpected_entries() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let (skills, sentinel) = store_with_sentinel(tmp.path());

        let plugin = prepare_ok(tmp.path(), &skills);
        plugin.cleanup().expect("first cleanup");
        plugin.cleanup().expect("a second cleanup is a no-op");
        sentinel_survives(&sentinel);

        // A fresh root with entries Tyde did not write. The root is Tyde-owned,
        // so they go with it — but a link planted among them must be unlinked
        // rather than followed to its target.
        let plugin = prepare_ok(tmp.path(), &skills);
        let wrapper = plugin.root().join("skills").join("alpha");
        std::fs::create_dir_all(wrapper.join("nested")).expect("intruder dir");
        std::fs::write(wrapper.join("nested").join("junk.txt"), "junk").expect("intruder file");
        symlink_path(&sentinel, &wrapper.join("planted-link")).expect("planted link");
        let root = plugin.root().to_path_buf();

        plugin.cleanup().expect("cleanup removes a Tyde-owned root whole");

        assert!(!root.exists());
        sentinel_survives(&sentinel);
    }

    /// The security contract, asserted per platform rather than assumed.
    ///
    /// On unix the root is `0700` and files are `0600` (see
    /// `the_root_and_its_files_are_private`). Anywhere else Tyde cannot yet
    /// prove that, so `prepare` must **refuse before the CLI process starts**
    /// rather than materialize a world-readable copy of the user's skill
    /// instructions. These two tests are mutually exclusive by `cfg`, so exactly
    /// one of them runs and neither platform is left silently untested.
    #[cfg(not(unix))]
    #[test]
    fn a_platform_without_private_directories_refuses_before_startup() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let store = tmp.path().join("store");
        let skills = vec![store_skill(&store, "alpha", "---\nname: alpha\n---\nbody\n")];

        let err = ClaudeSkillPlugin::prepare(Some(tmp.path()), &skills)
            .expect_err("an unprovable platform must fail, not fall back");

        assert!(err.contains("private"), "{err}");
        assert!(
            err.contains("world-readable"),
            "the reason must name the risk: {err}"
        );
    }

    #[cfg(unix)]
    #[test]
    fn unix_supports_private_roots_so_preparation_is_allowed() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let store = tmp.path().join("store");
        let skills = vec![store_skill(&store, "alpha", "---\nname: alpha\n---\nbody\n")];

        let plugin = prepare_ok(tmp.path(), &skills);

        assert!(
            plugin.root().exists(),
            "unix has the primitives, so preparation proceeds"
        );
    }

    #[test]
    fn init_frame_verification_requires_every_materialized_skill() {
        let expected = vec!["tyde-skills:a".to_string(), "tyde-skills:b".to_string()];

        assert_eq!(
            verify_init_frame(&expected, Some(&expected)),
            InitFrameVerdict::Verified
        );

        let missing = verify_init_frame(
            &expected,
            Some(&["tyde-skills:a".to_string(), "other".to_string()]),
        );
        assert!(
            matches!(missing, InitFrameVerdict::Failed(ref m) if m.contains("tyde-skills:b")),
            "{missing:?}"
        );

        let absent = verify_init_frame(&expected, None);
        assert!(
            matches!(absent, InitFrameVerdict::Failed(ref m) if m.contains("'skills' field")),
            "{absent:?}"
        );

        let collided = verify_init_frame(
            &expected,
            Some(&[
                "tyde-skills:a".to_string(),
                "tyde-skills:a".to_string(),
                "tyde-skills:b".to_string(),
            ]),
        );
        assert!(
            matches!(collided, InitFrameVerdict::Failed(ref m) if m.contains("collides")),
            "{collided:?}"
        );

        assert_eq!(verify_init_frame(&[], None), InitFrameVerdict::Verified);
    }

    #[test]
    fn plugin_flag_is_the_documented_one_only() {
        assert_eq!(CLAUDE_PLUGIN_DIR_FLAG, "--plugin-dir");
        assert!(help_text_supports_plugin_dir("  --plugin-dir <path>   Load a plugin"));
        assert!(!help_text_supports_plugin_dir("  --add-dir <path>"));
        assert!(unsupported_plugin_dir_error().contains("--plugin-dir"));
    }

    #[test]
    fn overlays_are_built_from_prepared_skills_only_and_carry_no_body() {
        let prepared: Vec<PreparedSkill> = (0..25)
            .map(|n| PreparedSkill {
                name: format!("skill{n}"),
                namespaced: namespaced_skill_name(&format!("skill{n}")),
                source_name: format!("skill{n}"),
                description: Some(format!("summary {n}")),
            })
            .collect();

        let one = native_skill_overlay(SkillSelection::AllInstalled, &prepared[..1]);
        let many = native_skill_overlay(SkillSelection::AllInstalled, &prepared);
        assert_eq!(one, many, "the Default overlay must be constant size");
        assert!(many.contains("tyde-skills:<name>"));
        for skill in &prepared {
            assert!(!many.contains(&skill.name), "Default must not enumerate: {many}");
        }

        let explicit = native_skill_overlay(SkillSelection::Explicit, &prepared[..2]);
        assert!(explicit.contains("skill0") && explicit.contains("summary 0"));
        assert!(!explicit.contains("skill2"), "only prepared skills appear: {explicit}");
        for overlay in [&one, &explicit] {
            assert!(!overlay.contains("Skill: "), "no legacy body block: {overlay}");
        }
    }

    #[test]
    fn the_degraded_notice_names_every_omitted_skill_and_reason() {
        let notice = degraded_default_notice(&[
            SkillRefusal { name: "a".to_string(), reason: "bad frontmatter".to_string() },
            SkillRefusal { name: "b".to_string(), reason: "unreadable".to_string() },
        ]);

        assert!(notice.contains("without 2 installed skill(s)"), "{notice}");
        assert!(notice.contains("skill 'a' was not exposed: bad frontmatter"), "{notice}");
        assert!(notice.contains("skill 'b' was not exposed: unreadable"), "{notice}");
    }

    #[test]
    fn body_bytes_survive_verbatim_including_whitespace() {
        // Leading blank lines, indentation, and trailing whitespace are all part
        // of a Markdown document's meaning; a wrapper must not reflow them.
        let body = "\n\n# Heading\n\n    indented block\n\nSee [art](art.md).\n\n- item\n   \n";
        let rendered = render_skill_md("x", Some("d"), body);

        assert!(
            rendered.ends_with(body),
            "the body must be appended byte for byte: {rendered:?}"
        );
        assert_eq!(
            &rendered[rendered.len() - body.len()..],
            body,
            "not one leading or trailing byte may be trimmed"
        );
        assert!(rendered.contains("](art.md)"));
        assert!(rendered.contains("    indented block"));
    }
}
